### ISSUE TITLE
Attempt to change table structure results in exception "file not found" in HHVM

### ISSUE THREAD

**Issue by r3wt** [phpmyadmin/phpmyadmin#11933]
Immediate Exception:

```
\nFatal error: Uncaught exception 'ReflectionException' with message 'Class PMA\\Controllers\\TableStructureController does not exist' in /usr/share/nginx5/html/mysql/libraries/session.inc.php:101\nStack trace:\n#0 /usr/share/nginx5/html/mysql/libraries/common.inc.php(350): include()\n#1 /usr/share/nginx5/html/mysql/navigation.php(10): include()\n#2 {main}
```
All requests there after until deleting session cookie, it crashes with same exception but deviations in stack trace:
```
\nFatal error: Uncaught exception 'ReflectionException' with message 'Class PMA\\Controllers\\TableStructureController does not exist' in /usr/share/nginx5/html/mysql/libraries/session.inc.php:101\nStack trace:\n#0 /usr/share/nginx5/html/mysql/libraries/common.inc.php(350): include()\n#1 /usr/share/nginx5/html/mysql/tbl_structure.php(14): include()\n#2 {main}
\nFatal error: Uncaught exception 'ReflectionException' with message 'Class PMA\\Controllers\\TableStructureController does not exist' in /usr/share/nginx5/html/mysql/libraries/session.inc.php:101\nStack trace:\n#0 /usr/share/nginx5/html/mysql/libraries/common.inc.php(350): include()\n#1 /usr/share/nginx5/html/mysql/index.php(12): include()\n#2 {main}
\nFatal error: Uncaught exception 'ReflectionException' with message 'Class PMA\\Controllers\\TableStructureController does not exist' in /usr/share/nginx5/html/mysql/libraries/session.inc.php:101\nStack trace:\n#0 /usr/share/nginx5/html/mysql/libraries/common.inc.php(350): include()\n#1 /usr/share/nginx5/html/mysql/index.php(12): include()\n#2 {main}
\nFatal error: Uncaught exception 'ReflectionException' with message 'Class PMA\\Controllers\\TableStructureController does not exist' in /usr/share/nginx5/html/mysql/libraries/session.inc.php:101\nStack trace:\n#0 /usr/share/nginx5/html/mysql/libraries/common.inc.php(350): include()\n#1 /usr/share/nginx5/html/mysql/db_structure.php(13): include()\n#2 {main}
\nFatal error: Uncaught exception 'ReflectionException' with message 'Class PMA\\Controllers\\TableStructureController does not exist' in /usr/share/nginx5/html/mysql/libraries/session.inc.php:101\nStack trace:\n#0 /usr/share/nginx5/html/mysql/libraries/common.inc.php(350): include()\n#1 /usr/share/nginx5/html/mysql/index.php(12): include()\n#2 {main}
\nFatal error: Uncaught exception 'ReflectionException' with message 'Class PMA\\Controllers\\TableStructureController does not exist' in /usr/share/nginx5/html/mysql/libraries/session.inc.php:105\nStack trace:\n#0 /usr/share/nginx5/html/mysql/libraries/common.inc.php(357): include()\n#1 /usr/share/nginx5/html/mysql/index.php(12): include()\n#2 {main}
```

```

**Comment by nijel** [comment]
What version do you use?

**Comment by r3wt** [comment]
bug occured under a previous version. i immediately installed latest version, and bug repeats. after delete session cookies, bug is gone. i can attempt to perform same action again

**Comment by r3wt** [comment]
hmm, i cant reproduce it now.

**Comment by nijel** [comment]
Okay, so let's assume this has been fixed. In case you can see it again, please reopen.
