### ISSUE TITLE
upload-release error

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12053]
`$ ./scripts/upload-release 4.6.0-rc1 release`

During the ssh call to `./bin/sync-files-cdn`, after the file transfer I get this:

```
total size is 9,079,773,550  speedup is 130.56
Added 4.6.0-rc1
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/builder/website/files/management/commands/import_files.py", line 85, in handle
    self.process_releases(os.path.join(settings.FILES_PATH, 'phpMyAdmin'))
  File "/home/builder/website/files/management/commands/import_files.py", line 81, in process_releases
    release
  File "/home/builder/website/files/management/commands/import_files.py", line 49, in process_files
    release=release, filename=filename
  File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 424, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 457, in _create_object_from_params
    obj.save(force_insert=True, using=self.db)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/builder/website/files/models.py", line 366, in purge_download
    purge_release(sender, instance.release)
  File "/home/builder/website/files/models.py", line 360, in purge_release
    instance.get_absolute_url(),
  File "/home/builder/website/pmaweb/cdn.py", line 55, in purge_cdn
    return perform(URL, data)
  File "/home/builder/website/pmaweb/cdn.py", line 40, in perform
    raise Exception(decoded)
Exception: {u'status': u'error', u'description': u"Purge is NOT successful because purging data didn't succeed."}
```

Only some files appear on the download page:
* phpMyAdmin-4.6.0-rc1-all-languages.7z 	6.0 MB 	[PGP] [MD5] [SHA1]
* phpMyAdmin-4.6.0-rc1-all-languages.tar.gz 	9.8 MB 	[PGP] [MD5] [SHA1]
* phpMyAdmin-4.6.0-rc1-all-languages.zip 	10.7 MB 	[PGP] [MD5] [SHA1]
* phpMyAdmin-4.6.0-rc1-english.7z 	4.2 MB 	[PGP] [MD5] [SHA1]
* phpMyAdmin-4.6.0-rc1-english.zip 	6.9 MB 	[PGP] [MD5] [SHA1]

**Comment by ibennetch** [comment]
I re-ran the script manually and it seems to have worked fine the second time.

**Comment by nijel** [comment]
Seems that CDN rejected the cache purge for some reason. I think it's correct to just fail in such case. All the sync scripts are safe to be executed multiple times.

**Comment by ibennetch** [comment]
I was thinking along the same lines, that it seemed to be some odd one-time failure and the second run worked fine, so I'll close this as something we can't reproduce.
