### ISSUE TITLE
Hidden dependency on ctype

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13162]
Since using Symfony ExpressionLanguage, we have hidden dependency on ctype (see https://github.com/phpmyadmin/docker/issues/115):

```
2017/04/06 15:41:37 [error] 25#25: *138 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ExpressionLanguage\ctype_digit() in /www/vendor/symfony/expression-language/Lexer.php:48
Stack trace:
#0 /www/vendor/symfony/expression-language/ExpressionLanguage.php(108): Symfony\Component\ExpressionLanguage\Lexer->tokenize('n > 1')
#1 /www/vendor/symfony/expression-language/ExpressionLanguage.php(81): Symfony\Component\ExpressionLanguage\ExpressionLanguage->parse('n > 1', Array)
#2 /www/vendor/phpmyadmin/motranslator/src/Translator.php(257): Symfony\Component\ExpressionLanguage\ExpressionLanguage->evaluate('n > 1', Array)
#3 /www/vendor/phpmyadmin/motranslator/src/Translator.php(285): PhpMyAdmin\MoTranslator\Translator->selectString(25)
#4 /www/vendor/phpmyadmin/motranslator/src/functions.php(108): PhpMyAdmin\MoTranslator\Translator->ngettext('%s table', '%s tables', 25)
#5 /www/templates/database/structure/body_for_table_summary.phtml(6): _ngettext('%s table', '%s tables', 25)
#6 /www/libraries/Template.php(15" while reading response header from upstream, client: 172.19.0.2, server: _, request: "GET /db_structure.php?db=mydb HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: "my.host.com"
```

Unfortunately this is not mentioned in composer metadata in ExpressionLanguage, so it went unnoticed. I've submitted PR there to removed this dependency: https://github.com/symfony/symfony/pull/22325

**Comment by udan11** [comment]
It looks like your pull request has been merged.

I think we should leave this issue open until v3.2.8 is released.

**Comment by nijel** [comment]
Indeed, makes sense.

**Comment by nijel** [comment]
It's already out, closing.
