### ISSUE TITLE
Twig introduces ctype dependecy

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13611]
After fixing this in 4.7 series (see https://github.com/phpmyadmin/phpmyadmin/issues/13162), the ctype dependecy is there again in master, this time through Twig:

```
PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function ctype_alpha() in /www/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:281

Stack trace:

#0 /www/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(99): Twig_Loader_Filesystem->isAbsolutePath('templates/')
#1 /www/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(82): Twig_Loader_Filesystem->addPath('templates/', '__main__')
#2 /www/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(40): Twig_Loader_Filesystem->setPaths(Array)
#3 /www/libraries/classes/Template.php(63): Twig_Loader_Filesystem->__construct('templates/')
#4 /www/libraries/classes/Template.php(93): PhpMyAdmin\Template->__construct('select_lang', Array, Array)
#5 /www/libraries/classes/LanguageManager.php(943): PhpMyAdmin\Template::get('select_lang')
#6 /www/libraries/classes/Plugins/Auth/AuthenticationCookie.php(169): PhpMyAdmin\LanguageManager->getSelectorDisplay(true, false)
#7 /www/libraries/common.inc.php(675): PhpMyAdmin\Plugins\Auth\AuthenticationCookie->auth()
#8 /www/ind
```

See https://travis-ci.org/phpmyadmin/docker/jobs/267602049

The question is whether we will really try to work without ctype or rather declare it as a dependency...

**Comment by nijel** [comment]
See also https://github.com/twigphp/Twig/issues/2051

**Comment by nijel** [comment]
If we decide to add ctype dependency, we could simplify some our code as well, at least in SQL parser:  phpmyadmin/sql-parser@5cb399390831abf8b524fa7815537d3cafccf143
