### ISSUE TITLE
[5.0.0-dev] Create database / strlen(false)

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14304]
### Steps to reproduce
1. Install PMA dev at c8bfcb7fb8f004b2d17ce0bea7065ec0d1dec65f
2. Go to "Create Database"

### Expected behaviour
Show create database

### Actual behaviour
Error 500

### More
Introduced by @mauriciofauth in 5f46a4ba52e7a264f04dee40159689ab0c8779bc

http://php.net/manual/en/function.array-search.php 
> Returns the key for needle if it is found in the array, FALSE otherwise.

https://github.com/phpmyadmin/phpmyadmin/blob/594cb7b1f286e433899007dc0cbdd53c40d734b7/libraries/classes/Controllers/Server/ServerDatabasesController.php#L418-L427

### Logs
```
2018/05/17 23:32:33 [error] 2654#2654: *481 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: strlen() expects parameter 1 to be string, boolean given in /mnt/Dev/phpmyadmintest/libraries/classes/Controllers/Server/ServerDatabasesController.php:422
Stack trace:
#0 /mnt/Dev/phpmyadmintest/libraries/classes/Controllers/Server/ServerDatabasesController.php(422): strlen(false)
#1 /mnt/Dev/phpmyadmintest/libraries/classes/Controllers/Server/ServerDatabasesController.php(389): PhpMyAdmin\Controllers\Server\ServerDatabasesController->_buildHtmlForDb(Array, Array, Array, Array, ' db-row')
#2 /mnt/Dev/phpmyadmintest/libraries/classes/Controllers/Server/ServerDatabasesController.php(300): PhpMyAdmin\Controllers\Server\ServerDatabasesController->_getHtmlForTableBody(Array, Array)
#3 /mnt/Dev/phpmyadmintest/libraries/classes/Controllers/Server/ServerDatabasesController.php(107): PhpMyAdmin\Controllers\Server\ServerDatabasesController->_getHtmlForDatabases(Array)
#4 /mnt/Dev/phpmyadmintest/server_databases.php(30): PhpMyAdmin\Controllers\Server\ServerDatabases" while reading response header from upstream, client: 127.0.0.1, server: localhost.localdomain, request: "GET /phpmyadmintest/server_databases.php?server=1&ajax_request=true&ajax_page_request=true&_nocache=1526592753773588097&token=E-%3E%3D%22MIGO-Pa1Q7O HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "localhost.localdomain"

```

**Comment by williamdes** [comment]
@mauriciofauth Another occurrence in `libraries/classes/Linter.php#160` with `mb_strlen`
https://github.com/phpmyadmin/phpmyadmin/blob/594cb7b1f286e433899007dc0cbdd53c40d734b7/libraries/classes/Linter.php#L160
```
Stack trace:
#0 /mnt/Dev/phpmyadmintest/libraries/classes/Linter.php(160): mb_strlen(NULL)
#1 /mnt/Dev/phpmyadmintest/lint.php(53): PhpMyAdmin\Linter::lint('CREATE DATABASE')
#2 {main}
  thrown in /mnt/Dev/phpmyadmintest/libraries/classes/Linter.php on line 160
NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: mb_strlen() expects parameter 1 to be string, null given in /mnt/Dev/phpmyadmintest/libraries/classes/Linter.php:160
```

**Comment by williamdes** [comment]
```
NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: Argument 4 passed to PhpMyAdmin\Export::getFilenameAndMimetype() must be of the type string, boolean given, called in /mnt/Dev/phpmyadmintest/export.php on line 355 and defined in /mnt/Dev/phpmyadmintest/libraries/classes/Export.php:274
Stack trace:
#0 /mnt/Dev/phpmyadmintest/export.php(355): PhpMyAdmin\Export->getFilenameAndMimetype('database', 'on', Object(PhpMyAdmin\Plugins\Export\ExportSql), false, '@DATABASE@')
#1 {main}
  thrown in /mnt/Dev/phpmyadmintest/libraries/classes/Export.php on line 274
```
https://github.com/phpmyadmin/phpmyadmin/blob/594cb7b1f286e433899007dc0cbdd53c40d734b7/export.php#L220
https://github.com/phpmyadmin/phpmyadmin/blob/594cb7b1f286e433899007dc0cbdd53c40d734b7/export.php#L353-L356
https://github.com/phpmyadmin/phpmyadmin/blob/594cb7b1f286e433899007dc0cbdd53c40d734b7/export.php#L353-L356

https://github.com/phpmyadmin/phpmyadmin/blob/594cb7b1f286e433899007dc0cbdd53c40d734b7/libraries/classes/Export.php#L263-L274
