### ISSUE TITLE
Uncaught TypeError: Return value of PhpMyAdmin\\Bookmark::getId()

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14303]
I don't know how I made this happen, but I got stuck in a situation where loading the login page gave me a blank page and this error in my logs:

> PHP Fatal error:  Uncaught TypeError: Return value of PhpMyAdmin\\Bookmark::getId() must be of the type integer, string returned in /var/www/pma-dev/fork/libraries/classes/Bookmark.php:79\nStack trace:\n#0 /var/www/pma-dev/fork/vendor/twig/twig/lib/Twig/Template.php(677): PhpMyAdmin\\Bookmark->getId()\n#1 /var/www/pma-dev/fork/tmp/twig/45/45dd19d30bf0cea7533af3f11f4dc24178a53e5289634d01177c8d3a4a676522.php(32): Twig_Template->getAttribute(Object(PhpMyAdmin\\Bookmark), 'getId', Array, 'method')\n#2 /var/www/pma-dev/fork/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_e3da5d3070451d403330999a0d8979c13af5ba55a16fa154c413b3a7cc55aa54->doDisplay(Array, Array)\n#3 /var/www/pma-dev/fork/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)\n#4 /var/www/pma-dev/fork/vendor/twig/twig/lib/Twig/Template.php(411): Twig_Template->display(Array)\n#5 /var/www/pma-dev/fork/vendor/twig/twig/lib/Twig/TemplateWrapper.php(43): Twig_Template->render(Array)\n#6 /var/www/pma-dev/fork/libraries/classes/Te in /var/www/pma-dev/fork/libraries/classes/Bookmark.php on line 79

I'm not sure how to trigger this. Clearing my browser cookies allowed me to log in, but after entering my username and password I get another blank page with the same error.

**Comment by ibennetch** [comment]
This appears to be caused by enabling strict mode in 6cf8ee083175a0a077b47103a3e32fdd76c669b6
