### ISSUE TITLE
Browse table - mb_substr 

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14457]
I can not send a table structure, this issue exists on my server.
I tried to copy table or database, this issue can not be copied.
This issue occurs with my user that is superuser, not with the user that "owns" the database
### Steps to reproduce
1. ?
2. TRUNCATE table
3. Browse table or Execute a search

URL: https://phpmyadmin.[DOMAIN]/sql.php?server=1&db=galeriev3&table=files&pos=0

### Expected behaviour
Show table

### Actual behaviour
Blank page or error 500
![bug1](https://user-images.githubusercontent.com/7784660/42289968-da3b6800-7fc2-11e8-8377-a93eb6d5d488.JPG)
![bug1-2](https://user-images.githubusercontent.com/7784660/42289969-da525830-7fc2-11e8-9b54-825999386314.JPG)

### Trace Browse & Search
```
PHP message: PHP Fatal error:  Uncaught TypeError: mb_substr() expects parameter 1 to be string, null given in /wwwroot/phpmyadmintest/libraries/classes/Display/Results.php:4706
Stack trace:
#0 /wwwroot/phpmyadmintest/libraries/classes/Display/Results.php(4706): mb_substr(NULL, 0, 50)
#1 /wwwroot/phpmyadmintest/libraries/classes/Display/Results.php(4399): PhpMyAdmin\Display\Results->_getSortedColumnMessage(Object(mysqli_result), '`path`')
#2 /wwwroot/phpmyadmintest/libraries/classes/Sql.php(1824): PhpMyAdmin\Display\Results->getTable(Object(mysqli_result), Array, Array, true)
#3 /wwwroot/phpmyadmintest/libraries/classes/Sql.php(1595): PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(Object(PhpMyAdmin\Display\Results), './themes/pmahom...', NULL, Array, false, 0, 0, true, Object(mysqli_result), Array, true)
#4 /wwwroot/phpmyadmintest/libraries/classes/Sql.php(2401): PhpMyAdmin\Sql->getQueryResponseForNoResultsReturned(Array, 'galeriev3', 'files', NULL, 0, Object(PhpMyAdmin\Display\Results), NULL, './themes/p" while reading response header from upstream, client: [IP_HERE], server: phpmyadmin.[DOMAIN], request: "GET /sql.php?server=1&db=galeriev3&table=files&pos=0&ajax_request=true&ajax_page_request=true&_nocache=1530724992189472572&token=K%3CJ%3FHeo%3FHJl%3E%5Cv3l HTTP/1.1", upstream: "fastcgi://unix:/wwwroot/sockets/php7-fpm-[DOMAIN].sock:", host: "phpmyadmin.[DOMAIN]"
```

### Screenshot of structure

![bug1-3](https://user-images.githubusercontent.com/7784660/42290348-067bc084-7fc5-11e8-8389-662f5e2b8755.JPG)

### Why
Is null :
https://github.com/phpmyadmin/phpmyadmin/blob/2d58411bee1dc33bc38198ea51349d469bc61ac5/libraries/classes/Display/Results.php#L4976

### Server configuration
**Operating system**: Debian

**Web server:** nginx/1.10.3

**Database:** MariaDB-10.2.14

**PHP version:** 7.2.6

**phpMyAdmin version:** 5.0.0-dev

[files.sql](https://github.com/phpmyadmin/phpmyadmin/files/2164041/files.sql.txt)

**Comment by williamdes** [comment]
Missed instance in #14317 see : https://github.com/phpmyadmin/phpmyadmin/pull/14317/files#diff-25c75771d2046495e6113414e54b5981

**Comment by williamdes** [comment]
@mauriciofauth I suspect demo server error to be this issue: https://demo.phpmyadmin.net/master-config/sql.php?server=2&db=opengis&table=gis_all&pos=0
