### ISSUE TITLE
strlen(false) getting called in Results.php

### ISSUE THREAD

**Issue by clearz** [phpmyadmin/phpmyadmin#14486]
### Steps to reproduce
1.
Create a db and run the following sql on it
CREATE TABLE `main` (
  `id` bigint(20) NOT NULL,
  `age` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `main` (`id`, `age`) VALUES (1, 37);

CREATE TABLE `names` (
  `id` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `names` (`id`, `name`) VALUES (1, 'John');
ALTER TABLE `main`  ADD PRIMARY KEY (`id`);
ALTER TABLE `names`  ADD PRIMARY KEY (`id`),
ADD KEY `fk_names_main_idx` (`id`);
ALTER TABLE `main`  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
ALTER TABLE `names`  ADD CONSTRAINT `fk_names_main` FOREIGN KEY (`id`) REFERENCES `main` (`id`)
ON DELETE NO ACTION ON UPDATE NO ACTION;

2.
run the standard select query "SELECT * FROM `names`" in the SQL tab or in the console at the bottom

### Expected behaviour
Show the rows in the table

### Actual behaviour
Fatal error: Uncaught TypeError: strlen() expects parameter 1 to be string, boolean given in C:\wamp64\apps\phpmyadmin5_beta\libraries\classes\Display\Results.php:5561 
Stack trace: #0 C:\wamp64\apps\phpmyadmin5_beta\libraries\classes\Display\Results.php(5561): strlen(false) 
#1 C:\wamp64\apps\phpmyadmin5_beta\libraries\classes\Display\Results.php(3794): PhpMyAdmin\Display\Results->_getRowData('right data grid...', false, Array, Object(stdClass), Array, '1', Array, Array, ' nowrap', ' = 1', Array, false, '') 
#2 C:\wamp64\apps\phpmyadmin5_beta\libraries\classes\Display\Results.php(3166): PhpMyAdmin\Display\Results->_getDataCellForNumericColumns('1', 'data grid_edit ...', false, Object(stdClass), Array, false, Array, Array, Array, Array) 
#3 C:\wamp64\apps\phpmyadmin5_beta\libraries\classes\Display\Results.php(2819): PhpMyAdmin\Display\Results->_getRowValues(Object(mysqli_result), Array, 0, false, Array, 'grid_edit click...', false, 'SELECT * FROM `...', Array) 
#4 C:\wamp64\apps\phpmyadmin5_beta\libraries\classes\Display\Resul in C:\wamp64\apps\phpmyadmin5_beta\libraries\classes\Display\Results.php on line 5561

If we check line 5561 the following is found strlen($map[$meta->name][2])
Running printf($map[$meta->name]) we get the following: Array ( [0] => main [1] => id [2] => [3] => mydb ) 
The problem seems to translate to running strlen(false)
Checking the variable for truthiness before calling strlen fixes the problem i.e !!$map[$meta->name][2]
but I'm not sure whether this is just placing a band-aid over a symptom of something else.

### Server configuration
Typical WAMPServer setup

**Operating system**:

**Web server:**
Apache 2

**Database:**
MySQL 5.7.19

**PHP version:**
7.1.9

**phpMyAdmin version:**
phpmyadmin5_beta

### Client configuration
**Browser:**
Firefox

**Operating system:**
Windows

**Comment by williamdes** [comment]
I am unable to reproduce this issue.
https://demo.phpmyadmin.net/QA_4_8/db_sql.php?db=williamdes
https://demo.phpmyadmin.net/master-config/db_sql.php?db=williamdes

@mauriciofauth You patched this issue with https://github.com/phpmyadmin/phpmyadmin/commit/13874a6937e78031741f858fad4eadd769cc3303
5 days ago

/close
