### ISSUE TITLE
Uncaught TypeError @ executeQueryAndGetQueryResponse

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14626]
When editing a row.. pMA a686ff8
```
Uncaught TypeError: Argument 9 passed to PhpMyAdmin\Sql::executeQueryAndGetQueryResponse() 
must be of the type string or null, object given, 
called in /srv/pma/libraries/classes/Sql.php on line 2295 
and defined in /srv/pma/libraries/classes/Sql.php:2329

Stack trace:
#0 /srv/pma/libraries/classes/Sql.php(2295): PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(Array, false, 'test', 't', NULL, NULL, NULL, NULL, Object(PhpMyAdmin\Message), NULL, 'sql.php?db=test...', './themes/pmahom...', NULL, NULL, NULL, 'SELECT * FROM `...', NULL, NULL)
#1 /srv/pma/sql.php(222): PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(Array, false, 'test', 't', NULL, NULL, NULL, NULL, Object(PhpMyAdmin\Message), NULL, 'sql.php?db=test...', './themes/pmahom...', NULL, NULL, NULL, 'SELECT * FROM `...', NULL, NULL)
#2 /srv/pma/tbl_replace.php(362): include('/srv/pma/sql.ph...')
#3 {main}
  thrown in /srv/pma/libraries/classes/Sql.php on line 2329
```

**Comment by mauriciofauth** [comment]
Fixed. Thanks, @OlafvdSpek.
