### ISSUE TITLE
str_pad() expects parameter 2 to be int, string given in libraries/classes/Util.php:2808

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14718]
str_pad() expects parameter 2 to be int, string given in /srv/pma/libraries/classes/Util.php:2808

```
PHP message: PHP Fatal error:  Uncaught TypeError: str_pad() expects parameter 2 to be int, string given in /srv/pma/libraries/classes/Util.php:2808
Stack trace:
#0 /srv/pma/libraries/classes/Util.php(2808): str_pad('1', '1', '0', 0)
#1 /srv/pma/libraries/classes/InsertEdit.php(2005): PhpMyAdmin\Util::printableBitValue('1', '1')
#2 /srv/pma/libraries/classes/InsertEdit.php(3209): PhpMyAdmin\InsertEdit->getSpecialCharsAndBackupFieldForExistingRow(Array, Array, Array, false, Array, '[multi_edit][0]...', false)
#3 /srv/pma/libraries/classes/InsertEdit.php(3474): PhpMyAdmin\InsertEdit->getHtmlForInsertEditFormColumn(Array, 49, Array, false, Object(mysqli_result), 'onchange', 0, '[multi_edit][0]', false, Array, 0, 49, 70, true, 3000, Array, 6000, 0, 'users', 'movie', 0, Array, 0, 'input', 'ltr', Array, Array, '`users`.`id` = ...')
```

**Comment by ibennetch** [comment]
Does this only happen with the development version/master/5.0.0-dev or is QA_4_8/release 4.8.3 also affected?

**Comment by OlafvdSpek** [comment]
I think it's just master.
