### ISSUE TITLE
is_uploaded_file() expects parameter 1 to be string

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14809]
When editing a row.. I didn't touch any binary fields.

```
PHP message: PHP Fatal error:  Uncaught TypeError: is_uploaded_file() expects parameter 1 to be string, null given in /srv/phpMyAdmin-5.0+snapshot-english/libraries/classes/File.php:230
Stack trace:
#0 /srv/phpMyAdmin-5.0+snapshot-english/libraries/classes/File.php(230): is_uploaded_file(NULL)
#1 /srv/phpMyAdmin-5.0+snapshot-english/libraries/classes/File.php(184): PhpMyAdmin\File->isUploaded()
#2 /srv/phpMyAdmin-5.0+snapshot-english/libraries/classes/File.php(214): PhpMyAdmin\File->getRawContent()
#3 /srv/phpMyAdmin-5.0+snapshot-english/tbl_replace.php(219): PhpMyAdmin\File->getContent()
#4 {main}
  thrown in /srv/phpMyAdmin-5.0+snapshot-english/libraries/classes/File.php on line 230
```

**Comment by bahl24** [comment]
@OlafvdSpek Can you please share some more details and screenshots to better describe the issue.

**Comment by OlafvdSpek** [comment]
What's unclear in `When editing a row.. I didn't touch any binary fields.`?

**Comment by williamdes** [comment]
@OlafvdSpek please send more details on how to reproduce this issue

**Comment by williamdes** [comment]
Reproduced !
Version: 5.0
Create a table with blob fields, then insert a row using files.
