### ISSUE TITLE
[opcache] PHPMyAdmin 4.8.4 Fatal Error - Twig_Error_Loader on Php 7.3.x

### ISSUE THREAD

**Issue by Deltafox79** [phpmyadmin/phpmyadmin#14824]
### Describe the bug

Am using PHPMyAdmin 4.8.4, MySQL 8.0.13, PHP 7.3.0, and Apache 2.4.37 mod_fcgid v2.3.9. Whenever I visit http://localhost/phpmyadmin/ I receive the following error:

> Fatal error: Uncaught Twig_Error_Loader: There are no registered paths for namespace "". in ...\phpmyadmin\vendor\twig\twig\lib\Twig\Loader\Filesystem.php on line 209

### To Reproduce

just launch the Phpmyadmin Script

### Expected behavior

> [Sun Dec 30 10:13:58.737987 2018] [fcgid:warn] [pid 19400:tid 1900] [client ::1:58774] mod_fcgid: stderr: PHP Fatal error:  Uncaught Twig_Error_Loader: There are no registered paths for namespace "". in ....\\phpmyadmin\\vendor\\twig\\twig\\lib\\Twig\\Loader\\Filesystem.php:209
[Sun Dec 30 10:13:58.737987 2018] [fcgid:warn] [pid 19400:tid 1900] [client ::1:58774] mod_fcgid: stderr: Stack trace:
[Sun Dec 30 10:13:58.737987 2018] [fcgid:warn] [pid 19400:tid 1900] [client ::1:58774] mod_fcgid: stderr: #0 ....\\phpmyadmin\\vendor\\twig\\twig\\lib\\Twig\\Loader\\Filesystem.php(150): Twig_Loader_Filesystem->findTemplate('select_lang.twi...')
[Sun Dec 30 10:13:58.737987 2018] [fcgid:warn] [pid 19400:tid 1900] [client ::1:58774] mod_fcgid: stderr: #1 ....\\phpmyadmin\\vendor\\twig\\twig\\lib\\Twig\\Environment.php(330): Twig_Loader_Filesystem->getCacheKey('select_lang.twi...')
[Sun Dec 30 10:13:58.737987 2018] [fcgid:warn] [pid 19400:tid 1900] [client ::1:58774] mod_fcgid: stderr: #2 ....\\phpmyadmin\\vendor\\twig\\twig\\lib\\Twig\\Environment.php(424): Twig_Environment->getTemplateClass('select_lang.twi...')
[Sun Dec 30 10:13:58.737987 2018] [fcgid:warn] [pid 19400:tid 1900] [client ::1:58774] mod_fcgid: stderr: #3 ....\\phpmyadmin\\vendor\\twig\\twig\\lib\\Twig\\Environment.php(402): Twig_Environment->loadTemplate('select_lang.twi...')
[Sun Dec 30 10:13:58.737987 2018] [fcgid:warn] [pid 19400:tid 1900] [client ::1:58774] mod_fcgid: stderr: #4 ....\\phpmyadmin\\libraries\\classes\\Template.php(115): Twig_Environment->load('select_lang.twi...')
[Sun Dec 30 10:13:58.737987 2018] [fcgid:warn] [pid 19400:tid 1900] [client ::1:58774] mod_fcgid: stderr: #5 ....\\phpmyadmin\\libraries\\classes\\LanguageManager.php(948): PhpMyAdmin\\Template->render(Array)
[Sun Dec 30 10:13:58.737987 2018] [fcgid:warn] [pid 19400:tid 1900] [client ::1:58774] mod_fcgid: stderr: #6 ....\\phpmyadmin\\libraries\\classes\\Plugins\\Auth\\AuthenticationCookie.php(143): PhpMyAdmin\\LanguageManager->getSelectorDisplay(true, false)
[Sun Dec 30 10:13:58.737987 2018] [fcgid:warn] [pid 19400:tid 1900] [client ::1:58774] mod_fcgid: stderr: #7 ....\\phpmyadmin\\vendor\\twig\\twig\\lib\\Twig\\Loader\\Filesystem.php on line 209

### Server configuration

- Operating system: 
Win 10 x64

Any Fix?

**Comment by ibennetch** [comment]
Hi, How have you installed phpMyAdmin? Did you download the source from phpmyadmin.net/downloads, clone the Git repository, use a package manager or prebuilt kit, etc?

**Comment by Deltafox79** [comment]
Hi I have just download 4.8.4 today here:

https://files.phpmyadmin.net/phpMyAdmin/4.8.4/phpMyAdmin-4.8.4-all-languages.zip

And only Edit config file.. Whit php 7.2.13 work fine but on php 7.3.0 I have this problems...

**Comment by ibennetch** [comment]
Hm, I've also tried with PHP 7.3.0 and I don't have any trouble, nor do I really have any insight as to what might be wrong. @mauriciofauth any ideas?

**Comment by Deltafox79** [comment]
> Hm, I've also tried with PHP 7.3.0 and I don't have any trouble, nor do I really have any insight as to what might be wrong. @mauriciofauth any ideas?

Also other user have this issue.. I find on the web :  

[https://stackoverflow.com/questions/53747548/phpmyadmin-fatal-error-twig-error-loader](https://stackoverflow.com/questions/53747548/phpmyadmin-fatal-error-twig-error-loader)

I will try to disable some extension and see if the situation is solved ...Regards

**Comment by Deltafox79** [comment]
Ok I have found the problem..
this line in php.ini :  

**`zend_extension = "C:\apache\php\ext\php_opcache.dll"`**

If enabled whit php 7.3.0 phpmyadmin goies on throw exception... can be fixed?

Regards

**Comment by williamdes** [comment]
I have a segfault using `7.3.0-2+ubuntu18.04.1+deb.sury.org+1` when browsing index.php of phpMyAdmin.
I had the issue but was thinking that it was php7.3 but thanks to you I can confirm it is `opcache`.

### Log level = 4
```
william@williamdes:/mnt/Dev/phpmyadmintest$ php7.3 -f index.php 
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/index.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key 'index.php:2331496:2236920'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/common.inc.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/vendor_config.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/hash.lib.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/autoload.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/composer/autoload_real.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/composer/ClassLoader.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/composer/include_paths.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/composer/autoload_static.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/symfony/polyfill-mbstring/bootstrap.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/paragonie/random_compat/lib/random.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../paragonie/random_compat/lib/random.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/symfony/polyfill-php56/bootstrap.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../symfony/polyfill-php56/bootstrap.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/phpseclib/phpseclib/phpseclib/bootstrap.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../phpseclib/phpseclib/phpseclib/bootstrap.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/phpmyadmin/motranslator/src/Loader.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../phpmyadmin/motranslator/src/Loader.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/phpmyadmin/motranslator/src/functions.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/ErrorHandler.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/ErrorHandler.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Core.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Core.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/symfony/polyfill-mbstring/Mbstring.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../symfony/polyfill-mbstring/Mbstring.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Config.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Config.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/config.default.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key './libraries/config.default.php:2331496:2524288:/mnt/Dev/phpmyadmintest/libraries/classes'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/config.inc.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key 'config.inc.php:2331496:2524288:/mnt/Dev/phpmyadmintest/libraries/classes'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/UserPreferences.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/UserPreferences.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Relation.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Relation.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Session.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Session.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Util.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Util.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/phpseclib/phpseclib/phpseclib/Crypt/Random.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../phpseclib/phpseclib/phpseclib/Crypt/Random.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Error.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Error.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Message.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Message.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Sanitize.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Sanitize.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/phpmyadmin/motranslator/src/Translator.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../phpmyadmin/motranslator/src/Translator.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/LanguageManager.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/LanguageManager.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Language.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Language.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/ThemeManager.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/ThemeManager.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Theme.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Theme.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/themes/pmahomme/layout.inc.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key './themes/pmahomme/layout.inc.php:2331496:2524288:/mnt/Dev/phpmyadmintest/libraries/classes'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/DatabaseInterface.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/DatabaseInterface.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Dbi/DbiMysqli.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Dbi/DbiMysqli.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Dbi/DbiExtension.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Dbi/DbiExtension.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Types.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Types.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Di/Container.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Di/Container.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/psr/container/src/ContainerInterface.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../psr/container/src/ContainerInterface.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Di/AliasItem.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Di/AliasItem.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Di/Item.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Di/Item.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Di/ValueItem.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Di/ValueItem.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Plugins/Auth/AuthenticationConfig.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Plugins/Auth/AuthenticationConfig.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Plugins/AuthenticationPlugin.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Plugins/AuthenticationPlugin.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Logging.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Logging.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Response.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Response.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/OutputBuffering.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/OutputBuffering.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Header.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Header.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Console.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Console.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Menu.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Menu.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Scripts.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Scripts.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Url.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Url.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/libraries/classes/Footer.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../../libraries/classes/Footer.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/phpmyadmin/sql-parser/src/Lexer.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../phpmyadmin/sql-parser/src/Lexer.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/phpmyadmin/sql-parser/src/Core.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../phpmyadmin/sql-parser/src/Core.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/phpmyadmin/sql-parser/src/TokensList.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../phpmyadmin/sql-parser/src/TokensList.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/phpmyadmin/sql-parser/src/Token.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../phpmyadmin/sql-parser/src/Token.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/phpmyadmin/sql-parser/src/Parser.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../phpmyadmin/sql-parser/src/Parser.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/phpmyadmin/sql-parser/src/Utils/Error.php'
Mon Dec 31 14:38:28 2018 (20867): Message Added key '/mnt/Dev/phpmyadmintest/vendor/composer/../phpmyadmin/sql-parser/src/Utils/Error.php'
Mon Dec 31 14:38:28 2018 (20867): Message Cached script '/mnt/Dev/phpmyadmintest/vendor/symfony/polyfill-mbstring/Resources/unidata/lowerCase.php'
Erreur de segmentation (core dumped)
```

**Comment by mauriciofauth** [comment]
@Deltafox79 @williamdes Can you try to reproduce this issue with PHP 7.3.2?

**Comment by Deltafox79** [comment]
> 
> 
> @Deltafox79 @williamdes Can you try to reproduce this issue with PHP 7.3.2?

Tested on Apache v2.4.38 Php 7.3.2 NTS and Phpmyadmin 4.8.5 everything seems to work properly..

![immagine](https://user-images.githubusercontent.com/2518850/52457924-98ad7180-2b5c-11e9-9dbf-2267cb6bafcc.jpg)

![immagine2](https://user-images.githubusercontent.com/2518850/52457946-bc70b780-2b5c-11e9-90c1-7ebd2ae0b484.jpg)

Regards

**Comment by williamdes** [comment]
Seems to be fixed.
