### ISSUE TITLE
union query result in server error 500

### ISSUE THREAD

**Issue by svaningelgem** [phpmyadmin/phpmyadmin#14888]
### Describe the bug

The problem arise when you do a union which is a wrong query.

### To Reproduce

Create any table (for example urls) with at least 1 field.
Create an invalid SQL:

```sql
select * from urls
union
select * from urls 
where abc = 123;
```

(abc = not existing in urls!)

### Expected behavior

Invalid SQL

### Observed behavior

Server error 500
(and in the PHP error log:)
```
Jan 22 14:27:02 calculation-server apache2[7361]: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpMyAdmin\Sql::resultSetHasJustOneTable() must be of the type array, null given, called in /usr/share/salvania-phpmyadmin/libraries/classes/Sql.php on line 1908 and defined in /usr/share/salvania-phpmyadmin/libraries/classes/Sql.php:143
Stack trace:
#0 /usr/share/salvania-phpmyadmin/libraries/classes/Sql.php(1908): PhpMyAdmin\Sql->resultSetHasJustOneTable(NULL)
#1 /usr/share/salvania-phpmyadmin/libraries/classes/Sql.php(2252): PhpMyAdmin\Sql->getQueryResponseForResultsReturned(false, Array, 'test', 'urls', NULL, NULL, Object(PhpMyAdmin\Display\Results), './themes/origin...', '1', 0, NULL, NULL, NULL, NULL, NULL, 'select * from u...', NULL)
#2 /usr/share/salvania-phpmyadmin/import.php(736): PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(Array, false, 'test', 'urls', NULL, NULL, NULL, NULL, NULL, NULL, 'db_sql.php', './themes/origin...', NULL, NULL, NULL, 'select * from u...', NULL, NULL)
#3 {main}
  thrown in /usr/share/salvania-phpmyadmin/libraries/classes/Sql.php on line 143

```

### Server configuration

- Operating system: Debian GNU/Linux 9.6 (stretch)
- Web server: Apache/2.4.25
- Database version: MySQL 5.6.42-log
- PHP version: PHP 7.2.13
- phpMyAdmin version: 4.8.4

### Client configuration

- Browser: Chrome 71.0.3578.98 64bit
- Operating system: Windows 7

**Comment by saurass** [comment]
@svaningelgem could you please share screenshots. I am unable to produce the error.

**Comment by svaningelgem** [comment]
Create table statement:
```
CREATE TABLE `urls` (
  `identifier` char(5) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `long` text COLLATE utf8_unicode_ci NOT NULL,
  `created` datetime NOT NULL,
  `used` datetime NOT NULL,
  PRIMARY KEY (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

Screenshot:
![image](https://user-images.githubusercontent.com/199434/51550869-944f3c00-1e6d-11e9-8b84-99e41163bd6d.png)


Log entry:
```
Jan 22 17:45:38 calculation-server apache2[22544]: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpMyAdmin\Sql::resultSetHasJustOneTable() must be of the type array, null given, called in /usr/share/salvania-phpmyadmin/libraries/classes/Sql.php on line 1908 and defined in /usr/share/salvania-phpmyadmin/libraries/classes/Sql.php:143#012Stack trace:#012#0 /usr/share/salvania-phpmyadmin/libraries/classes/Sql.php(1908): PhpMyAdmin\Sql->resultSetHasJustOneTable(NULL)#012#1 /usr/share/salvania-phpmyadmin/libraries/classes/Sql.php(2252): PhpMyAdmin\Sql->getQueryResponseForResultsReturned(false, Array, 'test', 'urls', NULL, NULL, Object(PhpMyAdmin\Display\Results), './themes/origin...', '1', 0, NULL, NULL, NULL, NULL, NULL, 'select * from u...', NULL)#012#2 /usr/share/salvania-phpmyadmin/import.php(736): PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(Array, false, 'test', 'urls', NULL, NULL, NULL, NULL, NULL, NULL, 'tbl_sql.php', './themes/origin...', NULL, NULL, NULL, 'select * from u...', NULL, NULL)#012#3 {main}#012  thrown in /usr/share/salvania-phpmyadmin/libraries/classes/Sql.php on line 143
```

**Comment by williamdes** [comment]
I am unable to reproduce this issue on demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

### Query
```sql
select * from urls union select * from urls where created = 123
 ```

**Comment by svaningelgem** [comment]
This is really strange. On the links you provided I cannot reproduce it either.
I will investigate a bit more indepth tomorrow to see why this is as it is. Because as I said, I can consistently get error 500.

**Comment by svaningelgem** [comment]
I can't reproduce this anymore in 4.8.5.
Closing the issue.
