### ISSUE TITLE
mb_strtoupper error in tbl_relation

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#15007]
I saw this in the error log, but I don't know how to reproduce it. Maybe we can figure it out, or maybe we'll just have to close this without enough information.

```2019/03/07 17:06:04 [error] 12839#12839: *37052822 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: mb_strtoupper() expects parameter 1 to be string, null given in /home/demo/.pma-demo/master-config/tbl_relation.php:49
Stack trace:
#0 /home/demo/.pma-demo/master-config/tbl_relation.php(49): mb_strtoupper(NULL)
#1 {main}
  thrown in /home/demo/.pma-demo/master-config/tbl_relation.php on line 49" while reading response header from upstream, client: 192.168.30.10, server: demo.phpmyadmin.net, request: "GET /master-config/tbl_relation.php?db=information_schema&table=INNODB_BUFFER_PAGE HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "demo.phpmyadmin.net"
2019/03/07 17:08:06 [error] 12839#12839: *37053457 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: mb_strtoupper() expects parameter 1 to be string, null given in /home/demo/.pma-demo/master-config/tbl_relation.php:49
Stack trace:
#0 /home/demo/.pma-demo/master-config/tbl_relation.php(49): mb_strtoupper(NULL)
#1 {main}
  thrown in /home/demo/.pma-demo/master-config/tbl_relation.php on line 49" while reading response header from upstream, client: 192.168.30.10, server: demo.phpmyadmin.net, request: "GET /master-config/tbl_relation.php?db=INFORMATION_SCHEMA&table=INNODB_TEMP_TABLE_INFO&server=2&target= HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "demo.phpmyadmin.net"
```

**Comment by williamdes** [comment]
Found nothing on report server.

**Comment by williamdes** [comment]
`tbl_relation.php?db=information_schema&table=INNODB_BUFFER_PAGE`

**Comment by williamdes** [comment]
Unable to reproduce, report if you see again this error and we will re-open this issue.
