### ISSUE TITLE
download of setup not working since 5254ec1b65fb21a88aceec405c159e62eda69394

### ISSUE THREAD

**Issue by Blaimi** [phpmyadmin/phpmyadmin#15337]
### Describe the bug

downloading the configuration from setup is not working since 5254ec1b65fb21a88aceec405c159e62eda69394

### To Reproduce

1. Go to /setup
2. Click on 'Download' or 'Display'
3. See error

```
[16-Jun-2019 23:55:04 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpMyAdmin\CheckUserPrivileges::__construct() must be an instance of PhpMyAdmin\DatabaseInterface, null given, called in /home/user/workspace/phpmyadmin/libraries/classes/Navigation/NavigationTree.php on line 113 and defined in /home/user/workspace/phpmyadmin/libraries/classes/CheckUserPrivileges.php:32
Stack trace:
#0 /home/user/workspace/phpmyadmin/libraries/classes/Navigation/NavigationTree.php(113): PhpMyAdmin\CheckUserPrivileges->__construct(NULL)
#1 /home/user/workspace/phpmyadmin/libraries/classes/Navigation/Navigation.php(61): PhpMyAdmin\Navigation\NavigationTree->__construct(Object(PhpMyAdmin\Template), NULL)
#2 /home/user/workspace/phpmyadmin/libraries/classes/Header.php(160): PhpMyAdmin\Navigation\Navigation->__construct(Object(PhpMyAdmin\Template), Object(PhpMyAdmin\Relation), NULL)
#3 /home/user/workspace/phpmyadmin/libraries/classes/Response.php(178): PhpMyAdmin\Header->__construct()
#4 /home/user/workspace/phpmyadmin/libraries/classes/Response.php(212):  in /home/user/workspace/phpmyadmin/libraries/classes/CheckUserPrivileges.php on line 32
[16-Jun-2019 23:55:04 UTC] PHP Fatal error:  Uncaught TypeError: chdir() expects parameter 1 to be a valid path, null given in /home/user/workspace/phpmyadmin/libraries/classes/Response.php:506
Stack trace:
#0 /home/user/workspace/phpmyadmin/libraries/classes/Response.php(506): chdir(NULL)
#1 [internal function]: PhpMyAdmin\Response->response()
#2 {main}
  thrown in /home/user/workspace/phpmyadmin/libraries/classes/Response.php on line 506

```

### Expected behavior

The configuration gets displayed or downloaded

### Server configuration

- Operating system: fedora 30
- Web server: Apache/2.4.39 (Fedora) 
- Database version:  10.3.12-MariaDB
- PHP version:  7.3.6
- phpMyAdmin version: a922b11 from master branch

### Client configuration

- Browser: firefox 67
- Operating system: fedora 30

### Additional context

The following patch fixes the problem but I don't think this is the intention of PMA_MINIMUM_COMMON and probably introduces new bugs because it ignores the is_empty($cfg['server'])-condition.

```patch
Index: libraries/common.inc.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- libraries/common.inc.php	(revision a922b1114ffadfaceabca1b9f140168956692c2d)
+++ libraries/common.inc.php	(date 1560730938000)
@@ -318,6 +318,14 @@
 
 $GLOBALS['dbi'] = null;
 
+/**
+ * Loads the proper database interface for this server
+ */
+$containerBuilder->set(DatabaseInterface::class, DatabaseInterface::load());
+$containerBuilder->setAlias('dbi', DatabaseInterface::class);
+$oldContainer->set(DatabaseInterface::class, $containerBuilder->get(DatabaseInterface::class));
+$oldContainer->alias('dbi', DatabaseInterface::class);
+
 if (! defined('PMA_MINIMUM_COMMON')) {
     /**
      * save some settings in cookies
@@ -328,13 +336,6 @@
     ThemeManager::getInstance()->setThemeCookie();
 
     if (! empty($cfg['Server'])) {
-        /**
-         * Loads the proper database interface for this server
-         */
-        $containerBuilder->set(DatabaseInterface::class, DatabaseInterface::load());
-        $containerBuilder->setAlias('dbi', DatabaseInterface::class);
-        $oldContainer->set(DatabaseInterface::class, $containerBuilder->get(DatabaseInterface::class));
-        $oldContainer->alias('dbi', DatabaseInterface::class);
 
         // get LoginCookieValidity from preferences cache
         // no generic solution for loading preferences from cache as some settings

```

**Comment by williamdes** [comment]
@mauriciofauth can you please have a look?

**Comment by mauriciofauth** [comment]
Fixed. Thanks, @Blaimi
