### ISSUE TITLE
error 500 when exporting - set time limit when $cfg['ExecTimeLimit'] used a string and not an int value

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15725]
Another user report that there is an error 500 when you try to export a database:

[28-Dec-2019 23:18:27 UTC] PHP Fatal error:  Uncaught TypeError: set_time_limit() expects parameter 1 to be integer, string given in /usr/local/nginx/html/25218_mysqladmin106/libraries/classes/Util.php:4842
Stack trace:
#0 /usr/local/nginx/html/25218_mysqladmin106/libraries/classes/Util.php(4842): set_time_limit('28800')
#1 /usr/local/nginx/html/25218_mysqladmin106/export.php(333): PhpMyAdmin\Util::setTimeLimit()
#2 {main}
  thrown in /usr/local/nginx/html/25218_mysqladmin106/libraries/classes/Util.php on line 4842

Didn't test that myself but you may want to check it...

Thanks

_Originally posted by @pamamolf in https://github.com/phpmyadmin/phpmyadmin/issues/15200#issuecomment-569812452_

**Comment by williamdes** [comment]
@pamamolf now fixed.
Please read the documentation and use int for in values or you will break more things
But I still agree that we should handle it on our side
