### ISSUE TITLE
php error using $cfg['ServerDefault'] = 0; on 5.0

### ISSUE THREAD

**Issue by trendchiller** [phpmyadmin/phpmyadmin#15761]
after copying an working existing config.inc.php from phpMyAdmin 4.9.4 to the phpMyAdmin 5.0.1 directory phpMyAdmin 5.0.1 shows only a white page.
Running _php index.php_ shows some error - perhaps that may help.

Running phpMyAdmin 5.0.1 without config works - generating a config from /setup leads to the same error...
```
[/share/Web/phpMyAdmin5] # /usr/local/apache/bin/php7.3 -v
PHP 7.3.7 (cli) (built: Dec  6 2019 05:00:41) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies

[/share/Web/phpMyAdmin5] # /usr/local/apache/bin/php7.3 index.php
Fatal error: Uncaught TypeError: chdir() expects parameter 1 to be a valid path, null given in libraries/classes/Response.php:506
Stack trace:
#0 libraries/classes/Response.php(506): chdir(NULL)
#1 [internal function]: PhpMyAdmin\Response->response()
#2 {main}
  thrown in libraries/classes/Response.php on line 506
```

**Comment by williamdes** [comment]
> Running phpMyAdmin 5.0.1 without config works - generating a config from /setup leads to the same error...

Thank you for the report, I will look into it ASAP

**Comment by JarnoVgr** [comment]
Had the same error. Work-around for me was changing `$cfg['ServerDefault'] = 0;` to `$cfg['ServerDefault'] = 1;`.

**Comment by williamdes** [comment]
Thank you so much @JarnoVgr I could reproduce this issue thanks to your comment !

**Comment by trendchiller** [comment]
I can confirm this, thank you !

**Comment by williamdes** [comment]
Also triggered #14312 
```
stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpMyAdmin\CheckUserPrivileges::__construct() must be an instance of PhpMyAdmin\DatabaseInterface, null given, called in libraries/classes/Navigation/NavigationTree.php on line 113 and defined in libraries/classes/CheckUserPrivileges.php:32"
172.21.0.14 -  14/Jan/2020:11:46:32 +0000 "GET /@phpmyadmin/theREALphpMyAdminREPO/index.php" 500
stderr: "Stack trace:"
stderr: "#0 libraries/classes/Navigation/NavigationTree.php(113): PhpMyAdmin\CheckUserPrivileges->__construct(NULL)"
stderr: "#1 libraries/classes/Navigation/Navigation.php(61): PhpMyAdmin\Navigation\NavigationTree->__construct(Object(PhpMyAdmin\Template), NULL)"
stderr: "#2 libraries/classes/Header.php(160): PhpMyAdmin\Navigation\Navigation->__construct(Object(PhpMyAdmin\Template), Object(PhpMyAdmin\Relation), NULL)"
stderr: "#3 libraries/classes/Response.php(17..."
stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: chdir() expects parameter 1 to be a valid path, null given in libraries/classes/Response.php:506"
stderr: "Stack trace:"
stderr: "#0 libraries/classes/Response.php(506): chdir(NULL)"
stderr: "#1 [internal function]: PhpMyAdmin\Response->response()"
stderr: "#2 {main}"
stderr: "  thrown in libraries/classes/Response.php on line 506"
```

**Comment by williamdes** [comment]
a686ff83601066f91396f4900dc3fd4bd25b2943 ?

**Comment by williamdes** [comment]
@JarnoVgr @trendchiller you can apply 876b6e13c48c160e17576a939ebfb7bd6af48f05 if you want to fix the issue before the snapshot is updated [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/)

The fix will be part of the next release
