### ISSUE TITLE
Cant display content from information_schema.PROCESSLIST

### ISSUE THREAD

**Issue by POPSuL** [phpmyadmin/phpmyadmin#15850]
### Describe the bug

Display nothing. Also, if you take manually select from this table, you're got that error:
```
Fatal error: Uncaught TypeError: trim() expects parameter 1 to be string, null given in /usr/share/phpMyAdmin/libraries/classes/Display/Results.php:2864 Stack trace: #0 /usr/share/phpMyAdmin/libraries/classes/Display/Results.php(2864): trim(NULL) #1 /usr/share/phpMyAdmin/libraries/classes/Display/Results.php(2614): PhpMyAdmin\Display\Results->_getRowValues(Object(mysqli_result), Array, 0, false, Array, '', false, 'select * from i...', Array) #2 /usr/share/phpMyAdmin/libraries/classes/Display/Results.php(4300): PhpMyAdmin\Display\Results->_getTableBody(Object(mysqli_result), Array, Array, Array, false) #3 /usr/share/phpMyAdmin/libraries/classes/Sql.php(1666): PhpMyAdmin\Display\Results->getTable(Object(mysqli_result), Array, Array, false) #4 /usr/share/phpMyAdmin/libraries/classes/Sql.php(2002): PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(Object(PhpMyAdmin\Display\Results), './themes/pmahom...', NULL, Array, false, false, 25, NULL, Object(mysqli_result), Array) #5 /usr/share/phpMyAdmin/libraries/classes/Sql.php(2271): P in /usr/share/phpMyAdmin/libraries/classes/Display/Results.php on line 2864
```

### To Reproduce

1. Go to SQL
2. execute `select * from information_schema.PROCESSLIST`
3. show nothing

### Expected behavior
Should shows process list

### Server configuration

CentOS, PHP 7.4, PMA 5.0.1

**Comment by rabeehrz** [comment]
I would like to work on this

**Comment by williamdes** [comment]
@rabeehrz You can work on this issue, please use QA_5_0 as base branch and target for your PR.
