### ISSUE TITLE
Uncaught TypeError: mb_strtolower() on Display Results

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16085]
```
NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: mb_strtolower() expects parameter 1 to be string, null given in /mnt/Dev/phpmyadmintest/libraries/classes/Display/Results.php:3103"
Stack trace:"
#0 libraries/classes/Display/Results.php(3103): mb_strtolower(NULL)"
#1 libraries/classes/Display/Results.php(2787): PhpMyAdmin\Display\Results->_getRowInfoForSpecialLinks(Array, Array)"
#2 libraries/classes/Display/Results.php(2629): PhpMyAdmin\Display\Results->_getRowValues(Object(mysqli_result), Array, 0, Array, Array, 'grid_edit click...', Array, 'SELECT (aaaaaa...', Array)"
#3 libraries/classes/Display/Results.php(4297): PhpMyAdmin\Display\Results->_getTableBody(Object(mysqli_result), Array, Array, Array, false)"
#4 libraries/classes/Sql.php(1534): PhpMyAdmin\Display\Results->getTable(Object(mysqli_result), Array, Array, false)"
#5 libraries/classes/Sql.php(1860):..."
```

Version: 5.0+

**Comment by williamdes** [comment]
```
NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: substr() expects parameter 1 to be string, null given in /mnt/Dev/phpmyadmintest/libraries/classes/Display/Results.php:3514"
Stack trace:"
#0 libraries/classes/Display/Results.php(3514): substr(NULL, 0, 9)"
#1 libraries/classes/Display/Results.php(2794): PhpMyAdmin\Display\Results->_getClassForDateTimeRelatedFields(NULL)"
#2 libraries/classes/Display/Results.php(2614): PhpMyAdmin\Display\Results->_getRowValues(Object(mysqli_result), Array, 0, Array, Array, 'grid_edit click...', Array, 'SELECT (aaaaaa...', Array)"
#3 libraries/classes/Display/Results.php(4301): PhpMyAdmin\Display\Results->_getTableBody(Object(mysqli_result), Array, Array, Array, false)"
#4 libraries/classes/Sql.php(1666): PhpMyAdmin\Display\Results->getTable(Object(mysqli_result), Array, Array, false)"
#5 libraries/classes/Sql.php(2002): PhpMyAdm..."
```

**Comment by williamdes** [comment]
```sql
SELECT (a * (b/100)) as acd,z.*  FROM `z` WHERE `v` = 61887 ORDER BY u asc
```

**Comment by williamdes** [comment]
```
NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: mb_strtolower() expects parameter 1 to be string, null given in /mnt/Dev/phpmyadmintest/libraries/classes/Display/Results.php:2861"
172.23.0.8 -  17/Apr/2020:13:12:10 +0000 "POST /index.php" 500
Stack trace:"
#0 libraries/classes/Display/Results.php(2861): mb_strtolower(NULL)"
#1 libraries/classes/Display/Results.php(2614): PhpMyAdmin\Display\Results->_getRowValues(Object(mysqli_result), Array, 0, Array, Array, 'grid_edit click...', Array, 'SELECT (aaaaaa...', Array)"
#2 libraries/classes/Display/Results.php(4301): PhpMyAdmin\Display\Results->_getTableBody(Object(mysqli_result), Array, Array, Array, false)"
#3 libraries/classes/Sql.php(1666): PhpMyAdmin\Display\Results->getTable(Object(mysqli_result), Array, Array, false)"
#4 libraries/classes/Sql.php(2002): PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(Object(PhpMyAdmin\Display\Results), './themes/pmahom...', NULL, Array, true, 1, 1, NULL, Obje..."
```

```
NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: mb_strtolower() expects parameter 1 to be string, null given in /mnt/Dev/phpmyadmintest/libraries/classes/Display/Results.php:2862"
172.23.0.8 -  17/Apr/2020:13:12:10 +0000 "POST /index.php" 500
Stack trace:"
#0 libraries/classes/Display/Results.php(2861): mb_strtolower(NULL)"
#1 libraries/classes/Display/Results.php(2614): PhpMyAdmin\Display\Results->_getRowValues(Object(mysqli_result), Array, 0, Array, Array, 'grid_edit click...', Array, 'SELECT (aaaaaa...', Array)"
#2 libraries/classes/Display/Results.php(4301): PhpMyAdmin\Display\Results->_getTableBody(Object(mysqli_result), Array, Array, Array, false)"
#3 libraries/classes/Sql.php(1666): PhpMyAdmin\Display\Results->getTable(Object(mysqli_result), Array, Array, false)"
#4 libraries/classes/Sql.php(2002): PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(Object(PhpMyAdmin\Display\Results), './themes/pmahom...', NULL, Array, true, 1, 1, NULL, Obje..."
```

```
NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: mysqli_result::fetch_field_direct() expects parameter 1 to be int, null given in libraries/classes/Dbi/DbiMysqli.php:568"
Stack trace:"
#0 libraries/classes/Dbi/DbiMysqli.php(568): mysqli_result->fetch_field_direct(NULL)"
#1 libraries/classes/DatabaseInterface.php(2980): PhpMyAdmin\Dbi\DbiMysqli->fieldFlags(Object(mysqli_result), NULL)"
#2 libraries/classes/Display/Results.php(3802): PhpMyAdmin\DatabaseInterface->fieldFlags(Object(mysqli_result), NULL)"
#3 libraries/classes/Display/Results.php(2988): PhpMyAdmin\Display\Results->_getDataCellForNonNumericColumns(NULL, 'data     ', NULL, Array, Array, false, Array, Array, Array, false, Array, Object(mysqli_result), NULL)"
#4 libraries/classes/Display/Results.php(2614): PhpMyAdmin\Display\Results->_getRowValues(Object(mysqli_result), Array, 0, Array, Array, 'grid_ed..."
172.23.0.8 -  17/Apr/2020:13:14:47 +0000 "POST /index.php" 500
```
