### ISSUE TITLE
php74 mbstring.func_overload = 2 how to combine mbstring.func_overload = 0

### ISSUE THREAD

**Issue by bagasik** [phpmyadmin/phpmyadmin#16313]
Hello.
My system FreeBSD 11.3
nginx + php74-fpm
```
php -v
PHP 7.4.9 (cli) (built: Aug 23 2020 16:38:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
```

Problem.
Bitrix site requires mbstring.func_overload = 2 parameter
phpmyadmin requires mbstring.func_overload = 0

I am setting up like this.
I create two FPM sockets
For the site and phpmyadmin.
In /usr/local/etc/php.ini specify the parameters (mbstring.func_overload = 2, mbstring.internal_encoding = utf-8).

```ini
;/usr/local/etc/php-fpm.d/www.conf
[bitrix]
listen = /tmp/www.sock
[pma]
listen = /tmp/pma.sock
php_admin_value[mbstring.func_overload] = 0
php_admin_value[mbstring.internal_encoding] =
```

```nginx
# nginx.conf
location /phpmyadmin/ {
alias /usr/local/www/phpMyAdmin/;
index index.php;
satisfy any;
allow 2.2.2.2;
deny all;
auth_basic "closed site";
auth_basic_user_file /usr/local/htpasswd;
location ~ \.php$ {
        fastcgi_pass unix:/tmp/pma.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $request_filename;
        fastcgi_ignore_client_abort off;
}
}
```

Phpmyadmin doesn't work.
I remember it worked for php72.
How to be?

```
2020/08/21 12:22:15 [error] 18866#100603: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Twig\Error\SyntaxError: Unexpected "lse" tag (expecting closing tag for the "if" tag defined near line 5). in /usr/local/www/phpMyAdmin/templates/display/results/comment_for_row.twig:6
Stack trace:
#0 /usr/local/www/phpMyAdmin/vendor/twig/twig/src/TokenParser/IfTokenParser.php(41): Twig\Parser->subparse()
#1 /usr/local/www/phpMyAdmin/vendor/twig/twig/src/Parser.php(209): Twig\TokenParser\IfTokenParser->parse()
#2 /usr/local/www/phpMyAdmin/vendor/twig/twig/src/TokenParser/IfTokenParser.php(41): Twig\Parser->subparse()
#3 /usr/local/www/phpMyAdmin/vendor/twig/twig/src/Parser.php(209): Twig\TokenParser\IfTokenParser->parse()
#4 /usr/local/www/phpMyAdmin/vendor/twig/twig/src/Parser.php(122): Twig\Parser->subparse()
#5 /usr/local/www/phpMyAdmin/vendor/twig/twig/src/Environment.php(735): Twig\Parser->parse()
#6 /usr/local/www/phpMyAdmin/vendor/twig/twig/src/Environment.php(793): Twig\Environment->parse()
#7 /usr/local/www/phpMyAdmin/vendor/twig/twig/src/Environmen" while reading response header from upstream, client: 1.2.3.1, server: local.local, request: "GET /phpmyadmin/sql.php?db=rw_new&table=b_catalog_currency_lang&pos=0&ajax_request=true&ajax_page_request=true&_nocache=1598001881989889313&token=5f7d76312760785d2136732269357660 HTTP/2.0", upstream: "fastcgi://unix:/tmp/pma.sock:", host: "local.local"
```

![photo-2020-08-21-15-44-59](https://user-images.githubusercontent.com/70150149/91055023-9f52eb00-e613-11ea-8f9a-5c0c2856a4a1.jpg)

**Comment by williamdes** [comment]
Hi @bagasik 

https://www.php.net/manual/en/mbstring.configuration.php#ini.mbstring.func-overload "This feature has been DEPRECATED as of PHP 7.2.0. Relying on this feature is highly discouraged."

I assume you do not need to configure it anymore.

I would recommend you to clean your `/usr/local/www/phpMyAdmin/tmp` directory and download  the latest version in development [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/)

Let me know if this error still occurs

**Comment by bagasik** [comment]
installed phpMyAdmin 5.1 + snapshot, didn't help, same error.
If so.
Default settings in /usr/local/etc/php.ini.
```
/usr/local/etc/php-fpm.d/www.conf
[bitrix]
listen = /tmp/www.sock
php_admin_value[mbstring.func_overload] = 2
[pma]
listen = /tmp/pma.sock
```
Site stops working, phpmyadmin works fine.

**Comment by programmistu** [comment]
https://github.com/composer/satis/issues/413
Twig 2 dropped any attempt to support it
