### ISSUE TITLE
Inspecting a table produces an exception: htmlspecialchars() expects parameter 1 to be string, null given

### ISSUE THREAD

**Issue by mbarchein** [phpmyadmin/phpmyadmin#16473]
Inspecting a table produces an exception using phpmyadmin 5.0.4

1. Go to database tables view
2. Click on affected table (others work)

```
Notice in ./libraries/classes/Display/Results.php#1086
 Undefined offset: 5

Backtrace

./libraries/classes/Display/Results.php#1220: PhpMyAdmin\Display\Results->_getTableHeadersForColumns(
array,
array,
array,
array,
array,
boolean false,
string 'SELECT * FROM `my_table` ',
)
./libraries/classes/Display/Results.php#4299: PhpMyAdmin\Display\Results->_getTableHeaders(
array,
array,
string 'SELECT * FROM `my_table` ',
array,
array,
array,
boolean false,
)
./libraries/classes/Sql.php#1669: PhpMyAdmin\Display\Results->getTable(
,
array,
array,
boolean false,
)
./libraries/classes/Sql.php#2007: PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(
,
string './themes/pmahomme/img/',
NULL,
array,
boolean true,
string '500558',
integer 25,
NULL,
,
array,
)
./libraries/classes/Sql.php#2276: PhpMyAdmin\Sql->getQueryResponseForResultsReturned(
,
array,
string 'my_database',
string 'my_table',
NULL,
NULL,
,
string './themes/pmahomme/img/',
string '500558',
integer 25,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'SELECT * FROM `my_table`',
NULL,
)
./libraries/classes/Sql.php#2105: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean true,
string 'my_database',
string 'my_table',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `my_table`',
NULL,
NULL,
)
./sql.php#242: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
array,
boolean true,
string 'my_database',
string 'my_table',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `my_table`',
NULL,
NULL,
)
./index.php#58: include(./sql.php)
```

```
 PHP Fatal error:  Uncaught TypeError: htmlspecialchars() expects parameter 1 to be string, null given in /var/www/html/libraries/classes/Display/Results.php:2065
Stack trace:
#0 /var/www/html/libraries/classes/Display/Results.php(2065): htmlspecialchars(NULL)
#1 /var/www/html/libraries/classes/Display/Results.php(1739): PhpMyAdmin\\Display\\Results->_getSortOrderLink('', NULL, 'sql.php?db=my_d...', 'sql.php?db=my_d...')
#2 /var/www/html/libraries/classes/Display/Results.php(1103): PhpMyAdmin\\Display\\Results->_getOrderLinkAndSortedHeaderHtml(NULL, Array, Array, NULL, 'SELECT * FROM `...', 25, '', Array, Array, NULL)
#3 /var/www/html/libraries/classes/Display/Results.php(1220): PhpMyAdmin\\Display\\Results->_getTableHeadersForColumns(Array, Array, Array, Array, Array, false, 'SELECT * FROM `...')
#4 /var/www/html/libraries/classes/Display/Results.php(4299): PhpMyAdmin\\Display\\Results->_getTableHeaders(Array, Array, 'SELECT * FROM `...', Array, Array, Array, false)
#5 /var/www/html/libraries/classes/Sql.php(1669): PhpMyAdmin\\Display\\ in /var/www/html/libraries/classes/Display/Results.php on line 2065
```

**Comment by williamdes** [comment]
Hi @mbarchein 
I added a fix for the issue you reported, when 5.1 is released this fix will be part of it.
You can download the daily snapshot on our [website](https://www.phpmyadmin.net/downloads/).
