### ISSUE TITLE
cannot access phpMyAdmin after upgrading to php 8.0

### ISSUE THREAD

**Issue by prepstarr** [phpmyadmin/phpmyadmin#16511]
### Describe the bug

Fatal error: Uncaught Error: Call to undefined function Symfony\Polyfill\Mbstring\iconv_strpos() in /usr/local/www/phpMyAdmin/vendor/symfony/polyfill-mbstring/Mbstring.php:501 Stack trace: #0 /usr/local/www/phpMyAdmin/vendor/symfony/polyfill-mbstring/bootstrap.php(60): Symfony\Polyfill\Mbstring\Mbstring::mb_strpos('&', ';', 0, 'UTF-8') #1 /usr/local/www/phpMyAdmin/libraries/classes/Url.php(257): mb_strpos('&', ';') #2 /usr/local/www/phpMyAdmin/libraries/classes/Url.php(208): PhpMyAdmin\Url::getArgSeparator() #3 /usr/local/www/phpMyAdmin/libraries/classes/Url.php(171): PhpMyAdmin\Url::getCommonRaw(Array, '?') #4 /usr/local/www/phpMyAdmin/libraries/classes/Core.php(765): PhpMyAdmin\Url::getCommon(Array) #5 /usr/local/www/phpMyAdmin/libraries/classes/Core.php(338): PhpMyAdmin\Core::linkURL('https://secure....') #6 /usr/local/www/phpMyAdmin/libraries/classes/Core.php(367): PhpMyAdmin\Core::getPHPDocLink('book.json.php') #7 /usr/local/www/phpMyAdmin/libraries/classes/Core.php(1009): PhpMyAdmin\Core::warnMissingExtension('json' in /usr/local/www/phpMyAdmin/vendor/symfony/polyfill-mbstring/Mbstring.php on line 501

### To Reproduce

In FreeBSD 12, 
pkg install php80 and then pkg install php80-extensions
then pkg install phpmyAdmin5

then ln -s location of phpmyadmin weburl

visit https://mywebsite.com/phpMyAdmin

### Expected behavior

Error 

Ideally you would login and it would work...

### Screenshots

no need

### Server configuration

- Operating system:freebsd12
- Web server:apache2.4.3
- Database version:mysql 8
- PHP version:8
- phpMyAdmin version:5.0.4

### Client configuration

- Browser:microsoft
- Operating system: windows 10 pro

### Additional context

the mb string iconv extensions were added as a means to debug this issue... I didn't want to reinstall a second version of phpmyAdmin but it was not working with the original ...

**Comment by prepstarr** [comment]
I think it might be a problem with php installation...

**Comment by prepstarr** [comment]
I am restoring it to the backup it was a big headache also I had to update the repository of pkg to latest. then make the update to get it available for freebsd . Also portsnap generated errors on the php80-extensions. And I think this is a php installation issue not phpMyAdmin...
