### ISSUE TITLE
Argument #1 ($offset) must be greater than or equal to 0

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16614]
5.1.0-rc1
PHP 8.0.1

When trying to browse an empty table:

```
PHP message: PHP Fatal error:  Uncaught ValueError: mysqli_result::data_seek(): Argument #1 ($offset) must be greater than or equal to 0 in /srv/phpMyAdmin-5.1+snapshot-english/libraries/classes/Dbal/DbiMysqli.php:308
Stack trace:
#0 /srv/phpMyAdmin-5.1+snapshot-english/libraries/classes/Dbal/DbiMysqli.php(308): mysqli_result->data_seek()
#1 /srv/phpMyAdmin-5.1+snapshot-english/libraries/classes/DatabaseInterface.php(2036): PhpMyAdmin\Dbal\DbiMysqli->dataSeek()
#2 /srv/phpMyAdmin-5.1+snapshot-english/libraries/classes/Display/Results.php(4339): PhpMyAdmin\DatabaseInterface->dataSeek()
#3 /srv/phpMyAdmin-5.1+snapshot-english/libraries/classes/Display/Results.php(4070): PhpMyAdmin\Display\Results->getSortedColumnMessage()
#4 /srv/phpMyAdmin-5.1+snapshot-english/libraries/classes/Sql.php(1356): PhpMyAdmin\Display\Results->getTable()
#5 /srv/phpMyAdmin-5.1+snapshot-english/libraries/classes/Sql.php(1157): PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable()
#6 /srv/phpMyAdmin-5.1+snapshot-english/librarie
```

**Comment by ibennetch** [comment]
Do you mean a table with no columns, or one that has columns but no data in it? I'm trying reproduce this and having trouble.

**Comment by RobertEcker** [comment]
I have the same problem with phpMyAdmin-5.1.0-rc2-all-languages

You can reproduce it with

```
CREATE TABLE `tbl_post` (
  `post_id` int(11) NOT NULL,
  `post_name` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


SELECT * FROM tbl_post ORDER BY post_id DESC

```


Fatal error: Uncaught ValueError: mysqli_result::data_seek(): Argument #1 ($offset) must be greater than or equal to 0
etc.

**Comment by williamdes** [comment]
Deleting **all** the rows of the last page of a table did trigger this for me.

I created #16633 to fix that

**Comment by ibennetch** [comment]
I've got it now, thank you.
