### ISSUE TITLE
Issue activating 2FA

### ISSUE THREAD

**Issue by mben42** [phpmyadmin/phpmyadmin#16638]
Hi,

I have this error when I try to activate 2FA:
```
Error in processing request
Error code: 500
Error text: Internal Server Error (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status.
```

Apache error.log:
```
PHP Fatal error:  Uncaught BaconQrCode\\Exception\\RuntimeException: You need to install the libxml extension to use this back end in /usr/share/phpmyadmin/vendor/bacon/bacon-qr-code/src/Renderer/Image/SvgImageBackEnd.php:46\nStack trace:\n#0 /usr/share/phpmyadmin/libraries/classes/Plugins/TwoFactor/Application.php(47): BaconQrCode\\Renderer\\Image\\SvgImageBackEnd->__construct()\n#1 /usr/share/phpmyadmin/libraries/classes/TwoFactor.php(272): PhpMyAdmin\\Plugins\\TwoFactor\\Application->__construct(Object(PhpMyAdmin\\TwoFactor))\n#2 /usr/share/phpmyadmin/prefs_twofactor.php(44): PhpMyAdmin\\TwoFactor->configure('application')\n#3 {main}\n  thrown in /usr/share/phpmyadmin/vendor/bacon/bacon-qr-code/src/Renderer/Image/SvgImageBackEnd.php on line 46
```

libxml is actually already installed:
```
# php -m
[PHP Modules]
calendar
Core
ctype
date
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
```

OS: Debian 10
PHP: 7.3.27
DB: MariaDB 10.3.27
Web server: Apache 2.4.38
phpMyAdmin: 5.0.4-all-languages

Thanks in advance

**Comment by ibennetch** [comment]
`php-m` shows the output of the command line PHP installation, which could differ from the one running web queries. Could you take a look through your browser at the output of `phpinfo()` to verify it's also present there?

**Comment by mben42** [comment]
How to do that?

**Comment by williamdes** [comment]
`apt install php7.3-xml`

**Comment by mben42** [comment]
Thank you, restart of apache2 is also required.
