### ISSUE TITLE
Error when visualizing nullable geometry column

### ISSUE THREAD

**Issue by M393** [phpmyadmin/phpmyadmin#16706]
### Describe the bug
Error when visualizing nullable geometry column.

### To Reproduce

1. Create table with nullable geometry
```sql
CREATE TABLE `a` (`p` polygon DEFAULT NULL);
INSERT INTO `a` (`p`) VALUES (NULL);
SELECT * FROM `a`;
```
2. Click on Visualize GIS data
3. See error

```
Error in GIS visualize with nullable Polygon column
<b>Fatal error</b>:  Uncaught TypeError: mb_strpos() expects parameter 1 to be string, null given in libraries\classes\Gis\GisVisualization.php:626
Stack trace:
#0 libraries\classes\Gis\GisVisualization.php(626): mb_strpos(NULL, '(')
#1 libraries\classes\Gis\GisVisualization.php(365): PhpMyAdmin\Gis\GisVisualization->scaleDataSet(Array)
#2 libraries\classes\Gis\GisVisualization.php(382): PhpMyAdmin\Gis\GisVisualization->svg()
#3 libraries\classes\Gis\GisVisualization.php(568): PhpMyAdmin\Gis\GisVisualization->asSVG()
#4 libraries\classes\Controllers\Table\GisVisualizationController.php(184): PhpMyAdmin\Gis\GisVisualization->toImage('svg')
#5 libraries\classes\Routing.php(186): PhpMyAdmin\Controllers\Table\GisVisualizationController->index(Array)
#6 index.php(18): PhpMyAdmin\Routing::callControllerForRoute('/table/gis-visu...', Object(FastRoute\Dispatcher\GroupCountBased), Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#7 {main}
  thrown in <b>libraries\classes\Gis\GisVisualization.php</b> on line <b>626</b>
```

### Expected behavior
Ignore null values for visualization.

### Server configuration
- Operating system: Windows 7
- Web server: Apache 2.4
- Database version: MySQL 5.7.29
- PHP version: 7.2
- phpMyAdmin version: 5.1

**Comment by williamdes** [comment]
Thank you @M393 for this report !
I could reproduce and fix this issue, I also added tests to cover it.
It will be fixed in the next 5.1 version.
