### ISSUE TITLE
PHP 8.0 - Uncaught ValueError: mysqli::query(): Argument #1 ($query) cannot be empty

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16730]
### Describe the bug

```
NOTICE: PHP message: PHP Fatal error:  Uncaught ValueError: mysqli::query(): Argument #1 ($query) cannot be empty in libraries/classes/Dbal/DbiMysqli.php:244
Stack trace:
#0 libraries/classes/Dbal/DbiMysqli.php(244): mysqli->query('', 0)
#1 libraries/classes/DatabaseInterface.php(213): PhpMyAdmin\Dbal\DbiMysqli->realQuery('', Object(mysqli), 1)
#2 libraries/classes/Sql.php(656): PhpMyAdmin\DatabaseInterface->tryQuery('', 256, 1)
#3 libraries/classes/Sql.php(869): PhpMyAdmin\Sql->executeQueryAndMeasureTime('')
#4 libraries/classes/Sql.php(1810): PhpMyAdmin\Sql->executeTheQuery(Array, '', true, '', '', NULL, NULL, NULL)
#5 libraries/classes/Sql.php(1700): PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(Array, tr...
```

### To Reproduce

1. Use #16724

### Server configuration

- PHP version: 8.1
- phpMyAdmin version: 5.1

**Comment by williamdes** [comment]
Should be fixed when #16724 is fixed
