### ISSUE TITLE
Export JSON issues with binary data

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16847]
- does not handle binary fields
- does not output text fields as text
- does not handle binary nullable data

### Server configuration

- phpMyAdmin version: 5.1

**Comment by williamdes** [comment]
```html
<br />
<b>Fatal error</b>:  Uncaught TypeError: bin2hex() expects parameter 1 to be string, null given in /mnt/Dev/@phpmyadmin/theREALphpMyAdminREPO/libraries/classes/Plugins/Export/ExportJson.php:277
Stack trace:
#0 /mnt/Dev/@phpmyadmin/theREALphpMyAdminREPO/libraries/classes/Plugins/Export/ExportJson.php(277): bin2hex(NULL)
#1 /mnt/Dev/@phpmyadmin/theREALphpMyAdminREPO/libraries/classes/Export.php(1117): PhpMyAdmin\Plugins\Export\ExportJson-&gt;exportData('test_cases_bina...', 'test_binary_fie...', '\n', 'index.php?route...', 'SELECT `id`, `n...', Array)
#2 /mnt/Dev/@phpmyadmin/theREALphpMyAdminREPO/libraries/classes/Controllers/ExportController.php(613): PhpMyAdmin\Export-&gt;exportTable('test_cases_bina...', 'test_binary_fie...', 'data', Object(PhpMyAdmin\Plugins\Export\ExportJson), '\n', 'index.php?route...', 'table', false, false, false, false, '1', '0', '0', '', Array)
#3 /mnt/Dev/@phpmyadmin/theREALphpMyAdminREPO/libraries/classes/Routing.php(186): PhpMyAdmin\Controllers\ExportController-&gt;index(Array)
#4 /mnt/Dev/@phpmyadmin/theREALph in <b>/mnt/Dev/@phpmyadmin/theREALphpMyAdminREPO/libraries/classes/Plugins/Export/ExportJson.php</b> on line <b>277</b><br />
```

**Comment by williamdes** [comment]
Dataset
```sql
START TRANSACTION;
CREATE TABLE `test_binary_fields` (
  `id` int(11) NOT NULL,
  `normalvc` varchar(25) COLLATE utf32_slovak_ci DEFAULT NULL,
  `binvc` varchar(25) CHARACTER SET utf32 COLLATE utf32_bin DEFAULT NULL,
  `bin` binary(32) DEFAULT NULL,
  `normaltext` text COLLATE utf32_slovak_ci DEFAULT NULL,
  `bintext` text CHARACTER SET utf32 COLLATE utf32_bin DEFAULT NULL,
  `medblob` mediumblob DEFAULT NULL,
  `blob` blob DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_slovak_ci;

INSERT INTO `test_binary_fields` (`id`, `normalvc`, `binvc`, `bin`, `normaltext`, `bintext`, `medblob`, `blob`) VALUES
(1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2, 'шеллы', 'шеллы', 0x0100000000000000000000000000000000000000000000000000000000000000, 'шеллы', 'шеллы', 0x2d2d207068704d7941646d696e2053514c2044756d700a2d2d2076657273696f6e20332e352e302d6465760a2d2d2068747470733a2f2f7777772e7068706d7961646d696e2e6e65740a2d2d0a2d2d20486f73743a20626172636c61790a2d2d2047656e65726174696f6e2054696d653a204175672030362c20323031312061742030343a353320504d0a2d2d205365727665722076657273696f6e3a20352e312e34392d332d6c6f670a2d2d205048502056657273696f6e3a20352e332e332d372b73717565657a65310a0a5345542053514c5f4d4f44453d224e4f5f4155544f5f56414c55455f4f4e5f5a45524f223b0a5345542074696d655f7a6f6e65203d20222b30303a3030223b0a0a0a2f2a2134303130312053455420404f4c445f4348415241435445525f5345545f434c49454e543d40404348415241435445525f5345545f434c49454e54202a2f3b0a2f2a2134303130312053455420404f4c445f4348415241435445525f5345545f524553554c54533d40404348415241435445525f5345545f524553554c5453202a2f3b0a2f2a2134303130312053455420404f4c445f434f4c4c4154494f4e5f434f4e4e454354494f4e3d4040434f4c4c4154494f4e5f434f4e4e454354494f4e202a2f3b0a2f2a21343031303120534554204e414d45532075746638202a2f3b0a0a44524f50204441544142415345204946204558495354532060223e3c7363726970743e616c65727428323030293b3c2f7363726970743e603b0a44524f50204441544142415345204946204558495354532060273e3c7363726970743e616c65727428323031293b3c2f7363726970743e603b0a44524f502044415441424153452049462045584953545320606578706c6f69745f74657374603b0a0a2d2d0a2d2d2044617461626173653a2060223e3c7363726970743e616c65727428323030293b3c2f7363726970743e600a2d2d0a4352454154452044415441424153452060223e3c7363726970743e616c65727428323030293b3c2f7363726970743e602044454641554c542043484152414354455220534554206c6174696e3120434f4c4c415445206c6174696e315f737765646973685f63693b0a0a2d2d0a2d2d2044617461626173653a2060273e3c7363726970743e616c65727428323031293b3c2f7363726970743e600a2d2d0a4352454154452044415441424153452060273e3c7363726970743e616c65727428323031293b3c2f7363726970743e602044454641554c542043484152414354455220534554206c6174696e3120434f4c4c415445206c6174696e315f737765646973685f63693b0a0a2d2d0a2d2d2044617461626173653a20606578706c6f69745f74657374600a2d2d0a43524541544520444154414241534520606578706c6f69745f74657374602044454641554c542043484152414354455220534554206c6174696e3120434f4c4c415445206c6174696e315f737765646973685f63693b0a55534520606578706c6f69745f74657374603b0a0a2d2d202d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d0a0a2d2d0a2d2d205461626c652073747275637475726520666f72207461626c652060223e3c7363726970743e616c65727428313039293b3c2f7363726970743e600a2d2d0a0a435245415445205441424c45204946204e4f54204558495354532060223e3c7363726970743e616c65727428313039293b3c2f7363726970743e6020280a20206069646020696e74283229204e4f54204e554c4c2c0a202060666f6f6020766172636861722832353529204e4f54204e554c4c0a2920454e47494e453d4d794953414d2044454641554c5420434841525345543d6c6174696e313b0a0a2d2d0a2d2d2044756d70696e67206461746120666f72207461626c652060223e3c7363726970743e616c65727428313039293b3c2f7363726970743e600a2d2d0a0a494e5345525420494e544f2060223e3c7363726970743e616c65727428313039293b3c2f7363726970743e602028606964602c2060666f6f60292056414c5545530a28312c202727292c0a28322c202727293b0a0a2d2d202d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d0a0a2d2d0a2d2d205461626c652073747275637475726520666f72207461626c652060273b20206576616c2827616c65727428313037292729600a2d2d0a0a435245415445205441424c45204946204e4f54204558495354532060273b20206576616c2827616c657274283130372927296020280a20206069646020696e7428313129204e4f54204e554c4c0a2920454e47494e453d4d794953414d2044454641554c5420434841525345543d6c6174696e313b0a0a2d2d202d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d0a0a2d2d0a2d2d205461626c652073747275637475726520666f72207461626c652060273e3c7363726970743e616c65727428313036293b3c2f7363726970743e600a2d2d0a0a435245415445205441424c45204946204e4f54204558495354532060273e3c7363726970743e616c65727428313036293b3c2f7363726970743e6020280a20206069646020696e74283229204e4f54204e554c4c0a2920454e47494e453d4d794953414d2044454641554c5420434841525345543d6c6174696e313b0a0a2d2d202d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d0a0a2d2d0a2d2d205461626c652073747275637475726520666f72207461626c6520603c7363726970743e616c65727428313035293b3c2f7363726970743e600a2d2d0a0a435245415445205441424c45204946204e4f542045584953545320603c7363726970743e616c65727428313035293b3c2f7363726970743e6020280a202060647361666020696e74283429204e4f54204e554c4c0a2920454e47494e453d4d794953414d2044454641554c5420434841525345543d6c6174696e313b0a0a2d2d0a2d2d2044756d70696e67206461746120666f72207461626c6520603c7363726970743e616c65727428313035293b3c2f7363726970743e600a2d2d0a0a494e5345525420494e544f20603c7363726970743e616c65727428313035293b3c2f7363726970743e602028606473616660292056414c5545530a2831293b0a0a2d2d202d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d0a0a2d2d0a2d2d205461626c652073747275637475726520666f72207461626c6520606576696c5f636f6c756d6e5f6e616d6573600a2d2d0a0a435245415445205441424c45204946204e4f542045584953545320606576696c5f636f6c756d6e5f6e616d65736020280a2020603c7363726970743e616c65727428313030293b3c2f7363726970743e6020696e74283129204e4f54204e554c4c2c0a202060223e3c7363726970743e616c65727428313031293b3c2f7363726970743e6020696e74283229204e4f54204e554c4c2c0a202060273e3c7363726970743e616c65727428313032293b3c2f7363726970743e6020696e74283229204e4f54204e554c4c2c0a2020606576696c5f636f6d6d656e746020696e74283329204e4f54204e554c4c20434f4d4d454e5420273c7363726970743e616c65727428313034293b3c2f7363726970743e270a2920454e47494e453d4d794953414d2044454641554c5420434841525345543d6c6174696e313b0a0a2d2d0a2d2d2044756d70696e67206461746120666f72207461626c6520606576696c5f636f6c756d6e5f6e616d6573600a2d2d0a0a494e5345525420494e544f20606576696c5f636f6c756d6e5f6e616d6573602028603c7363726970743e616c65727428313030293b3c2f7363726970743e602c2060223e3c7363726970743e616c65727428313031293b3c2f7363726970743e602c2060273e3c7363726970743e616c65727428313032293b3c2f7363726970743e602c20606576696c5f636f6d6d656e7460292056414c5545530a28312c2032332c2034352c2035292c0a28322c20332c2037372c2033293b0a0a2d2d202d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d0a0a2d2d0a2d2d205461626c652073747275637475726520666f72207461626c6520606576696c5f636f6e74656e74600a2d2d0a0a435245415445205441424c45204946204e4f542045584953545320606576696c5f636f6e74656e746020280a09202060746578746020766172636861722832353529204e4f54204e554c4c0a092920454e47494e453d4d794953414d2044454641554c5420434841525345543d6c6174696e313b0a0a0a2d2d0a2d2d2044756d70696e67206461746120666f72207461626c6520606576696c5f636f6e74656e74600a2d2d0a0a494e5345525420494e544f20606576696c5f636f6e74656e74602028607465787460292056414c5545530a2827223e3c7363726970743e616c65727428333031293b3c2f7363726970743e27292c0a282727273e3c7363726970743e616c65727428333032293b3c2f7363726970743e27292c0a28273c7363726970743e616c65727428333033293b3c2f7363726970743e27292c0a282727273b20206576616c282727616c65727428333034292727293b27293b0a0a2d2d202d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d0a0a2d2d0a2d2d205461626c652073747275637475726520666f72207461626c6520606576696c5f7461626c655f636f6d6d656e74600a2d2d0a0a435245415445205441424c45204946204e4f542045584953545320606576696c5f7461626c655f636f6d6d656e746020280a20206069646020696e74283129204e4f54204e554c4c0a2920454e47494e453d4d794953414d2044454641554c5420434841525345543d6c6174696e3120434f4d4d454e543d27223e3c7363726970743e616c65727428343030293b3c2f7363726970743e273b0a0a0a2f2a21343031303120534554204348415241435445525f5345545f434c49454e543d404f4c445f4348415241435445525f5345545f434c49454e54202a2f3b0a2f2a21343031303120534554204348415241435445525f5345545f524553554c54533d404f4c445f4348415241435445525f5345545f524553554c5453202a2f3b0a2f2a2134303130312053455420434f4c4c4154494f4e5f434f4e4e454354494f4e3d404f4c445f434f4c4c4154494f4e5f434f4e4e454354494f4e202a2f3b0a, 0x2d2d207068704d7941646d696e2053514c2044756d700a2d2d2076657273696f6e20332e352e302d6465760a2d2d2068747470733a2f2f7777772e7068706d7961646d696e2e6e65740a2d2d0a2d2d20486f73743a20626172636c61790a2d2d2047656e65726174696f6e2054696d653a204175672030362c20323031312061742030343a353320504d0a2d2d205365727665722076657273696f6e3a20352e312e34392d332d6c6f670a2d2d205048502056657273696f6e3a20352e332e332d372b73717565657a65310a0a5345542053514c5f4d4f44453d224e4f5f4155544f5f56414c55455f4f4e5f5a45524f223b0a5345542074696d655f7a6f6e65203d20222b30303a3030223b0a0a0a2f2a2134303130312053455420404f4c445f4348415241435445525f5345545f434c49454e543d40404348415241435445525f5345545f434c49454e54202a2f3b0a2f2a2134303130312053455420404f4c445f4348415241435445525f5345545f524553554c54533d40404348415241435445525f5345545f524553554c5453202a2f3b0a2f2a2134303130312053455420404f4c445f434f4c4c4154494f4e5f434f4e4e454354494f4e3d4040434f4c4c4154494f4e5f434f4e4e454354494f4e202a2f3b0a2f2a21343031303120534554204e414d45532075746638202a2f3b0a0a44524f50204441544142415345204946204558495354532060223e3c7363726970743e616c65727428323030293b3c2f7363726970743e603b0a44524f50204441544142415345204946204558495354532060273e3c7363726970743e616c65727428323031293b3c2f7363726970743e603b0a44524f502044415441424153452049462045584953545320606578706c6f69745f74657374603b0a0a2d2d0a2d2d2044617461626173653a2060223e3c7363726970743e616c65727428323030293b3c2f7363726970743e600a2d2d0a4352454154452044415441424153452060223e3c7363726970743e616c65727428323030293b3c2f7363726970743e602044454641554c542043484152414354455220534554206c6174696e3120434f4c4c415445206c6174696e315f737765646973685f63693b0a0a2d2d0a2d2d2044617461626173653a2060273e3c7363726970743e616c65727428323031293b3c2f7363726970743e600a2d2d0a4352454154452044415441424153452060273e3c7363726970743e616c65727428323031293b3c2f7363726970743e602044454641554c542043484152414354455220534554206c6174696e3120434f4c4c415445206c6174696e315f737765646973685f63693b0a0a2d2d0a2d2d2044617461626173653a20606578706c6f69745f74657374600a2d2d0a43524541544520444154414241534520606578706c6f69745f74657374602044454641554c542043484152414354455220534554206c6174696e3120434f4c4c415445206c6174696e315f737765646973685f63693b0a55534520606578706c6f69745f74657374603b0a0a2d2d202d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d0a0a2d2d0a2d2d205461626c652073747275637475726520666f72207461626c652060223e3c7363726970743e616c65727428313039293b3c2f7363726970743e600a2d2d0a0a435245415445205441424c45204946204e4f54204558495354532060223e3c7363726970743e616c65727428313039293b3c2f7363726970743e6020280a20206069646020696e74283229204e4f54204e554c4c2c0a202060666f6f6020766172636861722832353529204e4f54204e554c4c0a2920454e47494e453d4d794953414d2044454641554c5420434841525345543d6c6174696e313b0a0a2d2d0a2d2d2044756d70696e67206461746120666f72207461626c652060223e3c7363726970743e616c65727428313039293b3c2f7363726970743e600a2d2d0a0a494e5345525420494e544f2060223e3c7363726970743e616c65727428313039293b3c2f7363726970743e602028606964602c2060666f6f60292056414c5545530a28312c202727292c0a28322c202727293b0a0a2d2d202d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d0a0a2d2d0a2d2d205461626c652073747275637475726520666f72207461626c652060273b20206576616c2827616c65727428313037292729600a2d2d0a0a435245415445205441424c45204946204e4f54204558495354532060273b20206576616c2827616c657274283130372927296020280a20206069646020696e7428313129204e4f54204e554c4c0a2920454e47494e453d4d794953414d2044454641554c5420434841525345543d6c6174696e313b0a0a2d2d202d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d0a0a2d2d0a2d2d205461626c652073747275637475726520666f72207461626c652060273e3c7363726970743e616c65727428313036293b3c2f7363726970743e600a2d2d0a0a435245415445205441424c45204946204e4f54204558495354532060273e3c7363726970743e616c65727428313036293b3c2f7363726970743e6020280a20206069646020696e74283229204e4f54204e554c4c0a2920454e47494e453d4d794953414d2044454641554c5420434841525345543d6c6174696e313b0a0a2d2d202d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d0a0a2d2d0a2d2d205461626c652073747275637475726520666f72207461626c6520603c7363726970743e616c65727428313035293b3c2f7363726970743e600a2d2d0a0a435245415445205441424c45204946204e4f542045584953545320603c7363726970743e616c65727428313035293b3c2f7363726970743e6020280a202060647361666020696e74283429204e4f54204e554c4c0a2920454e47494e453d4d794953414d2044454641554c5420434841525345543d6c6174696e313b0a0a2d2d0a2d2d2044756d70696e67206461746120666f72207461626c6520603c7363726970743e616c65727428313035293b3c2f7363726970743e600a2d2d0a0a494e5345525420494e544f20603c7363726970743e616c65727428313035293b3c2f7363726970743e602028606473616660292056414c5545530a2831293b0a0a2d2d202d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d0a0a2d2d0a2d2d205461626c652073747275637475726520666f72207461626c6520606576696c5f636f6c756d6e5f6e616d6573600a2d2d0a0a435245415445205441424c45204946204e4f542045584953545320606576696c5f636f6c756d6e5f6e616d65736020280a2020603c7363726970743e616c65727428313030293b3c2f7363726970743e6020696e74283129204e4f54204e554c4c2c0a202060223e3c7363726970743e616c65727428313031293b3c2f7363726970743e6020696e74283229204e4f54204e554c4c2c0a202060273e3c7363726970743e616c65727428313032293b3c2f7363726970743e6020696e74283229204e4f54204e554c4c2c0a2020606576696c5f636f6d6d656e746020696e74283329204e4f54204e554c4c20434f4d4d454e5420273c7363726970743e616c65727428313034293b3c2f7363726970743e270a2920454e47494e453d4d794953414d2044454641554c5420434841525345543d6c6174696e313b0a0a2d2d0a2d2d2044756d70696e67206461746120666f72207461626c6520606576696c5f636f6c756d6e5f6e616d6573600a2d2d0a0a494e5345525420494e544f20606576696c5f636f6c756d6e5f6e616d6573602028603c7363726970743e616c65727428313030293b3c2f7363726970743e602c2060223e3c7363726970743e616c65727428313031293b3c2f7363726970743e602c2060273e3c7363726970743e616c65727428313032293b3c2f7363726970743e602c20606576696c5f636f6d6d656e7460292056414c5545530a28312c2032332c2034352c2035292c0a28322c20332c2037372c2033293b0a0a2d2d202d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d0a0a2d2d0a2d2d205461626c652073747275637475726520666f72207461626c6520606576696c5f636f6e74656e74600a2d2d0a0a435245415445205441424c45204946204e4f542045584953545320606576696c5f636f6e74656e746020280a09202060746578746020766172636861722832353529204e4f54204e554c4c0a092920454e47494e453d4d794953414d2044454641554c5420434841525345543d6c6174696e313b0a0a0a2d2d0a2d2d2044756d70696e67206461746120666f72207461626c6520606576696c5f636f6e74656e74600a2d2d0a0a494e5345525420494e544f20606576696c5f636f6e74656e74602028607465787460292056414c5545530a2827223e3c7363726970743e616c65727428333031293b3c2f7363726970743e27292c0a282727273e3c7363726970743e616c65727428333032293b3c2f7363726970743e27292c0a28273c7363726970743e616c65727428333033293b3c2f7363726970743e27292c0a282727273b20206576616c282727616c65727428333034292727293b27293b0a0a2d2d202d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d0a0a2d2d0a2d2d205461626c652073747275637475726520666f72207461626c6520606576696c5f7461626c655f636f6d6d656e74600a2d2d0a0a435245415445205441424c45204946204e4f542045584953545320606576696c5f7461626c655f636f6d6d656e746020280a20206069646020696e74283129204e4f54204e554c4c0a2920454e47494e453d4d794953414d2044454641554c5420434841525345543d6c6174696e3120434f4d4d454e543d27223e3c7363726970743e616c65727428343030293b3c2f7363726970743e273b0a0a0a2f2a21343031303120534554204348415241435445525f5345545f434c49454e543d404f4c445f4348415241435445525f5345545f434c49454e54202a2f3b0a2f2a21343031303120534554204348415241435445525f5345545f524553554c54533d404f4c445f4348415241435445525f5345545f524553554c5453202a2f3b0a2f2a2134303130312053455420434f4c4c4154494f4e5f434f4e4e454354494f4e3d404f4c445f434f4c4c4154494f4e5f434f4e4e454354494f4e202a2f3b0a);

ALTER TABLE `test_binary_fields`
  ADD UNIQUE KEY `id` (`id`);

ALTER TABLE `test_binary_fields`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;
```
