### ISSUE TITLE
[ODS Import] Uncaught TypeError: PhpMyAdmin\Import::detectType(): Argument #2 ($cell) must be of type ?string, float given

### ISSUE THREAD

**Issue by mokraemer** [phpmyadmin/phpmyadmin#16920]
The give stacktrace is:

```
PHP Fatal error:  Uncaught TypeError: PhpMyAdmin\Import::detectType(): Argument #2 ($cell) must be of type ?string, float given, called in /usr/share/phpmyadmin/libraries/classes/Import.php on line 977 and defined in /usr/share/phpmyadmin/libraries/classes/Import.php:890
Stack trace:
#0 /usr/share/phpmyadmin/libraries/classes/Import.php(977): PhpMyAdmin\Import->detectType()
#1 /usr/share/phpmyadmin/libraries/classes/Plugins/Import/ImportOds.php(207): PhpMyAdmin\Import->analyzeTable()
#2 /usr/share/phpmyadmin/libraries/classes/Controllers/ImportController.php(635): PhpMyAdmin\Plugins\Import\ImportOds->doImport()
#3 /usr/share/phpmyadmin/libraries/classes/Routing.php(186): PhpMyAdmin\Controllers\ImportController->index()
#4 /usr/share/phpmyadmin/index.php(18): PhpMyAdmin\Routing::callControllerForRoute()
#5 {main}
  thrown in /usr/share/phpmyadmin/libraries/classes/Import.php on line 890

```

the line is:
$curr_type = $this->detectType($types[$i], $table[self::ROWS][$j][$i]);

it looks like the second argument is not as expected.

**Comment by williamdes** [comment]
Hi @mokraemer
Could you provide us the failing file or a sample file that also reproduces the failure?

**Comment by mokraemer** [comment]
[import.ods](https://github.com/phpmyadmin/phpmyadmin/files/6553879/import.ods)

Here is the requested file

**Comment by williamdes** [comment]
I could reproduce and fix this error, thank you for reporting it !

```
Fatal error: Uncaught TypeError: PhpMyAdmin\Import::detectType(): Argument #2 ($cell) must be of type ?string, float given, called in
libraries/classes/Import.php on line 977 and defined in
libraries/classes/Import.php:890 Stack trace: #0
libraries/classes/Import.php(977): PhpMyAdmin\Import->detectType(1, 0.13) #1
libraries/classes/Plugins/Import/ImportOds.php(207): PhpMyAdmin\Import->analyzeTable(Array) #2
libraries/classes/Controllers/ImportController.php(635): PhpMyAdmin\Plugins\Import\ImportOds->doImport(Object(PhpMyAdmin\File), Array) #3
libraries/classes/Routing.php(187): PhpMyAdmin\Controllers\ImportController->index(Array) #4
index.php(18): PhpMyAdmin\Routing::callControllerForRoute('/import', Object(FastRoute\Dispatcher\GroupCountBased), Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #5 {main} thrown in
libraries/classes/Import.php on line 890
```

**Comment by mokraemer** [comment]
thanks for fixing!

**Comment by williamdes** [comment]
> thanks for fixing!

You can try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) it will include the fix :)
