### ISSUE TITLE
Undefined index: utf8mb3

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16931]
### Describe the bug

```
Notice: Undefined index: utf8mb3
#2 ./libraries/classes/Charsets.php(18): callControllerForRoute
#1 ./libraries/classes/Charsets.php(186): index
#0 ./libraries/classes/Charsets.php(163): getServerCharset
```

### To Reproduce

No idea

### Expected behavior

No php notice

### Server configuration

- Database version: ?
- phpMyAdmin version: 5.1

### Additional context

Reported many times and affects quite a bunch of users (at least 5).

**Comment by williamdes** [comment]
For members having access to our Sentry back-end, error: `PHPMYADMIN-1G`

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: utf8mb3
 Exception Type |php
 phpMyAdmin version |5.0.0
 Incident count | 11
 Link | [Report#70614](https://reports.phpmyadmin.net/reports/view/70614)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
Found on the error reporting server for phpMyAdmin versions: 5.0, 5.1, 5.2.0-dev (so one of the users is a tester)
Nothing installation specific. Would be glad to know the DBMS the users have

**Comment by williamdes** [comment]
Found it on StackOverflow: https://stackoverflow.com/q/67421885/5155484

Will try to reproduce and fix this issue

**Comment by williamdes** [comment]
On a MySQL 8, run `SET GLOBAL character_set_server = 'utf8';`
The warning `Warning: #3719 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.` will be printed
Go to homepage:

![image](https://user-images.githubusercontent.com/7784660/120184512-59b1f700-c211-11eb-8719-e43644df014c.png)
