### ISSUE TITLE
Latest deb is broken

### ISSUE THREAD

**Issue by garak** [phpmyadmin/phpmyadmin#16968]
### Describe the bug

I just updated a server of mine, using [PPA](https://launchpad.net/~phpmyadmin/+archive/ubuntu/ppa).
I see that current version is `4:5.1.1+dfsg1-2+focal1`, while previous was (apparently) `4:5.0.4+dfsg2-2~bpo10+1+focal1`.

Nothing is working anymore, I started getting strange errors in log, with complains about Symfony missing files (first services.yml, then services_controllers.yml). After creating such files, error is `Unknown named parameter $$dbi in /usr/share/php/Symfony/Component/DependencyInjection/ContainerBuilder.php:1140`. The web interface is always in error 500.

### To Reproduce

Not sure about it

### Expected behavior

Working phpmyadmin

### Server configuration

- Operating system: Ubuntu 20.04.2 LTS
- Web server: nginx/1.18.0
- Database version: mysql  Ver 8.0.25-0ubuntu0.20.04.1
- PHP version: PHP 8.0.7
- phpMyAdmin version: 5.1.1

**Comment by williamdes** [comment]
Hi @garak !
This is really strange, looks like the upgrade did not work at all, can you re-install the package ?

On all my tests it worked fine, this is why I am quite surprised

**Comment by garak** [comment]
I just tried to remove package (via apt), delete by hand `/usr/share/phpmyadmin/` directory, reinstall the package.
No luck.
I'm still getting `PHP Fatal error:  Uncaught Error: Unknown named parameter $$response in /usr/share/php/Symfony/Component/DependencyInjection/ContainerBuilder.php:1140`

**Comment by williamdes** [comment]
Do you have opcache ?
What version of `apt info php-symfony-dependency-injection` do you have installed ?

**Comment by garak** [comment]
> Do you have opcache ?

I do.

> What version of `apt info php-symfony-dependency-injection` do you have installed ?

Package: php-symfony-dependency-injection
Version: 4.3.8+dfsg-1ubuntu1

**Comment by williamdes** [comment]
> I do.

Can you purge it ?

> Package: php-symfony-dependency-injection
Version: 4.3.8+dfsg-1ubuntu1

Just checked and `ubuntu1` has no source code changed in the patch

**Comment by garak** [comment]
I don't think opcache can survive between restarts, but anyway I tried to disable it (see attached screenshot from phpinfo).
Error is still there.
![Schermata da 2021-06-17 17-19-38](https://user-images.githubusercontent.com/179866/122426264-631cbc80-cf90-11eb-9368-091d189f68b6.png)

**Comment by williamdes** [comment]
You can confirm the error is still talking about `services.yml, then services_controllers.yml` ?

**Comment by garak** [comment]
No, it's only about "Unknown named parameter $$response" now.
Moreover, I updated phpmyadmin on a different server (with Ubuntu 18.04 instead of 20.04) and I get the same error.

**Comment by williamdes** [comment]
> No, it's only about "Unknown named parameter $$response" now.
> Moreover, I updated phpmyadmin on a different server (with Ubuntu 18.04 instead of 20.04) and I get the same error.

Hi!
That could be https://github.com/phpmyadmin/phpmyadmin/issues/16301
I will try with php 8
cc @utkarsh2102

**Comment by williamdes** [comment]
You will need to upgrade phpmyadmin to ` 4:5.1.1+dfsg1-3+{focal,bionic}1` and then upgrade `php-symfony-dependency-injection` to a v5 version

The versions passed build and are in upload stage, I think in ~30min they should be available

**Comment by garak** [comment]
I upgraded to 4:5.1.1+dfsg1-3+focal1, but php-symfony-dependency-injection only exists in version 4 on Ubuntu (even on latest version, see https://packages.ubuntu.com/hirsute/php-symfony-dependency-injection).
Error is still the same.

**Comment by williamdes** [comment]
> Error is still the same.

Yup, but it is now ouf of our control :/ (I feel bad about it but I can not do much more)

You have the following solutions:
- use PHP 7
- add another apt source to find the `php-symfony-dependency-injection` v5 (like debian experimental)
- go into the files and hack the code to apply the diff as said in https://serverfault.com/a/1052827/336084 (https://github.com/phpmyadmin/phpmyadmin/issues/16620#issuecomment-830107985)

**Comment by garak** [comment]
Each of such alternative looks like a poor solution.
Why can't you fix your deb?

**Comment by williamdes** [comment]
> Each of such alternative looks like a poor solution.
> Why can't you fix your deb?

Because the problem is not in our deb but in a deb we do not control 😿

**Comment by williamdes** [comment]
@utkarsh2102 do you think it would be easy to fire a build of symfony into the PPA ?

**Comment by garak** [comment]
> Because the problem is not in our deb but in a deb we do not control crying_cat_face

Don't get me wrong, but this sounds like an excuse. Your deb should be able to work with its current dependencies.

**Comment by williamdes** [comment]
> > Because the problem is not in our deb but in a deb we do not control crying_cat_face
> 
> Don't get me wrong, but this sounds like an excuse. Your deb should be able to work with its current dependencies.

Don't get me wrong, it is not an excuse but a real problem :)
The packaging does not work like a normal composer update, it uses dependencies that are packaged by other people.
The best I can do would be to try to build they dependency and push it into the PPA so you can upgrade it.

> Your deb should be able to work with its current dependencies.

The deb says (`apt info ../phpmyadmin_5.1.1+dfsg1-3_all.deb`):
```
Depends: dbconfig-mysql | dbconfig-no-thanks | dbconfig-common (<< 2.0.0), libjs-bootstrap4, libjs-codemirror, libjs-jquery, libjs-jquery-mousewheel, libjs-jquery-timepicker, libjs-jquery-ui, php-cli, sensible-utils, ucf, debconf (>= 0.5) | debconf-2.0, php-common, php-json, php-mysql, php-xml, php-google-recaptcha (>= 1.1), php-google-recaptcha (<< 2~~),
 php-nikic-fast-route (>= 1.3), php-nikic-fast-route (<< 2~~), php-phpmyadmin-motranslator (>= 5.0), php-phpmyadmin-motranslator (<< 6~~), php-phpmyadmin-shapefile (>= 2.0), php-phpmyadmin-shapefile (<< 3~~),
 php-phpmyadmin-sql-parser (>= 5.0), php-phpmyadmin-sql-parser (<< 6~~),
 php-twig-i18n-extension (>= 3.0), php-twig-i18n-extension (<< 4~~), php-phpseclib (>= 2.0), php-phpseclib (<< 3~~), php-symfony-config (>= 4.4.9), php-symfony-config (<< 6~~), php-symfony-dependency-injection (>= 4.4.9),
 php-symfony-dependency-injection (<< 6~~), php-symfony-expression-language (>= 4.4.9),
 php-symfony-expression-language (<< 6~~), php-mbstring, php-twig (>= 2.9), php-twig (<< 4~~), php-mariadb-mysql-kbs (>= 1.2), php-mariadb-mysql-kbs (<< 2~~), libjs-sphinxdoc (>= 1.0)
```

You can clearly see it says, we accept v3,v4,v5 versions of `php-symfony-dependency-injection`.
The contents is not the problem of our deb from this point.

**Comment by garak** [comment]
But you said above that I must use v5, because v4 is not working.
So, what's the meaning of "accepting" something your deb is not working with?

**Comment by williamdes** [comment]
> But you said above that I must use v5, because v4 is not working.
> So, what's the meaning of "accepting" something your deb is not working with?

v3, v4, v5 is working perfectly with PHP 7

it's up to them to have working code on PHP 8 and up to other people to make the updates
but you know it is done by volunteers, so the updates can sometime take too long and not be available in your Ubuntu/Debian release

**Comment by garak** [comment]
I filed a [bug on launchpad](https://bugs.launchpad.net/ubuntu/+source/symfony/+bug/1932552). Let's hope to see it handled soon.
I think you should keep this bug open (or reference somewhere that current deb is not working with php8).

**Comment by williamdes** [comment]
> or reference somewhere that current deb is not working with php8

Seems like this is a missing mechanism in the packaging of PHP packages, I did not see any way to indicate PHP version compatibility

> Let's hope to see it handled soon.

@utkarsh2102 do you think it can receive a patch ?

**Comment by utkarsh2102** [comment]
Hello 👋🏻,

I've commented on the bug & marked it as "Fix Released" since we have newer symfony on newer releases:
```
$ rmadison symfony    
ubuntu:
 symfony | 2.7.10-0ubuntu2       | xenial/universe          | source
 symfony | 3.4.6+dfsg-1          | bionic/universe          | source
 symfony | 3.4.6+dfsg-1ubuntu0.1 | bionic-security/universe | source
 symfony | 3.4.6+dfsg-1ubuntu0.1 | bionic-updates/universe  | source
 symfony | 4.3.8+dfsg-1ubuntu1   | focal/universe           | source
 symfony | 4.4.14+dfsg-1         | groovy/universe          | source
 symfony | 4.4.19+dfsg-1         | hirsute/universe         | source
 symfony | 4.4.19+dfsg-1         | impish/universe          | source
 symfony | 5.2.6+dfsg-1ubuntu7   | impish-proposed/universe | source
```

The version in Impish (-proposed), that is, 5.2.6+dfsg-1ubuntu7, works well with PHP 8.0. We're in midst of the transition and gradually the migration of symfony should happen in a couple of days from -proposed to -release. But it'll be available in Impish only.

**Comment by williamdes** [comment]
Thank you @utkarsh2102 

I think one of the solutions 

Currently the [patch](https://github.com/symfony/symfony/commit/8e34978e4e2c4bf7dac97e44e904368c4cfb54f8) is part of the following symfony releases

>  v5.3.2  v5.3.1 v5.3.0 v5.3.0-RC1 v5.3.0-BETA4 v5.3.0-BETA3 v5.3.0-BETA2 v5.3.0-BETA1 v5.2.10 v5.2.9 v5.2.8 v5.2.7 v5.2.6 v5.2.5 v5.2.4 v5.2.3 v5.2.2 v5.2.1 v5.2.0 v5.2.0-RC2 v5.2.0-RC1 v5.2.0-BETA3 v5.2.0-BETA2 v5.2.0-BETA1 v5.1.11 v5.1.10 v5.1.9 v5.1.8 v5.1.7 v5.1.6 v4.4.25 v4.4.24 v4.4.23 v4.4.22 v4.4.21 v4.4.20 v4.4.19 v4.4.18 v4.4.17 v4.4.16 v4.4.15 v4.4.14 v3.4.49 v3.4.48 v3.4.47 v3.4.46 v3.4.45

So adding `groovy` as a source would allow installing a newer version of `php-symfony-dependency-injection`

**Comment by garak** [comment]
Just a quick note to report that newer version (4:5.1.1+dfsg1-3+focal1) is not working either.

**Comment by williamdes** [comment]
> Just a quick note to report that newer version (4:5.1.1+dfsg1-3+focal1) is not working either.

Hi @garak 
What do you call "not working either"
Could you post the stacktrace ?

**Comment by garak** [comment]
> What do you call "not working either"
> Could you post the stacktrace ?

It's just the same as above. I thought the problem was already triaged

**Comment by williamdes** [comment]
> > What do you call "not working either"
> > Could you post the stacktrace ?
> 
> It's just the same as above. I thought the problem was already triaged

It is :)
The symfony problem has nothing to do with us, @utkarsh2102 asked for the fix to be integrated into latest LTS at Ubuntu.

**Comment by KimHEF** [comment]
Hello Guys,

i had the same issue that phpmyadmin gave me the Error500 after Login. Then i tried the solution with adding the "array_values" like here [https://github.com/symfony/symfony/commit/8e34978e4e2c4bf7dac97e44e904368c4cfb54f8]. It worked for the first moment and the Login is possible but i can't enter the "Structure"-Tab. So what is the best Solution now? The Groovy Package Thing?

**Comment by williamdes** [comment]
Hello @KimHEF 

Thank you for the feedback :)

> but i can't enter the "Structure"-Tab

If it is not the symfony error, can you post the error log here ?

> So what is the best Solution now? The Groovy Package Thing?

Yeah, wait for a Ubuntu package team person to apply the patch and release the package for LTS users

**Comment by KimHEF** [comment]
It looks like Symfony but don't know...

` PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, stdClass given in /usr/share/php/Twig/Extension/CoreExtension.php:1608\nStack trace:\n#0 /var/lib/phpmyadmin/tmp/twig/bf/bfdb615ba339b0ebedc9d167771071703d4db3a77a3cb08205b080de13f3183d.php(187): twig_get_attribute()\n#1 /usr/share/php/Twig/Template.php(184): __TwigTemplate_0ff364d332e700064d43333fa838025d35529b1baedbdb1e75f647491d1b4d6d->block_content()\n#2 /var/lib/phpmyadmin/tmp/twig/2c/2cf2548fcf36278f0adab25eaa4b5a26fe228ad4dc1532b36b742e89875183ae.php(74): Twig\\Template->displayBlock()\n#3 /usr/share/php/Twig/Template.php(395): __TwigTemplate_bc8f94527caf3b40a29e806cc96b205c2ae5f17b256a23e829f653650bd28fc3->doDisplay()\n#4 /usr/share/php/Twig/Template.php(372): Twig\\Template->displayWithErrorHandling()\n#5 /var/lib/phpmyadmin/tmp/twig/bf/bfdb615ba339b0ebedc9d167771071703d4db3a77a3cb08205b080de13f3183d.php(40): Twig\\Template->display()\n#6 /usr/share/php/Twig/Template.php(395): __TwigTemplate_0ff364d332e700064d43333fa838025d35529b1baedbdb1e75f647491d1b4d6d->doDisplay()\n#7 /usr/share/php/Twig/Template.php(372): Twig\\Template->displayWithErrorHandling()\n#8 /usr/share/php/Twig/Template.php(380): Twig\\Template->display()\n#9 /usr/share/php/Twig/TemplateWrapper.php(45): Twig\\Template->render()\n#10 /usr/share/phpmyadmin/libraries/classes/Template.php(132): Twig\\TemplateWrapper->render()\n#11 /usr/share/phpmyadmin/libraries/classes/Controllers/Table/StructureController.php(1565): PhpMyAdmin\\Template->render()\n#12 /usr/share/phpmyadmin/libraries/classes/Controllers/Table/StructureController.php(171): PhpMyAdmin\\Controllers\\Table\\StructureController->displayStructure()\n#13 /usr/share/phpmyadmin/libraries/classes/Routing.php(187): PhpMyAdmin\\Controllers\\Table\\StructureController->index()\n#14 /usr/share/phpmyadmin/index.php(18): PhpMyAdmin\\Routing::callControllerForRoute()\n#15 {main}\n  thrown in /usr/share/php/Twig/Extension/CoreExtension.php on line 1608`

**Comment by williamdes** [comment]
Not very clear what it could be, I would `rm -rf /var/lib/phpmyadmin/tmp/twig/*` as a first step

**Comment by KimHEF** [comment]
Changed nothing...

**Comment by williamdes** [comment]
> Changed nothing...

Since the trace is cryptic, could you send here the line and lines around it that are reported on the trace ?

for example: `/var/lib/phpmyadmin/tmp/twig/bf/bfdb615ba339b0ebedc9d167771071703d4db3a77a3cb08205b080de13f3183d.php(187)`
Lines 100 to 200

**Comment by KimHEF** [comment]
[bfdb615ba339b0ebedc9d167771071703d4db3a77a3cb08205b080de13f3183d.php.txt](https://github.com/phpmyadmin/phpmyadmin/files/6744220/bfdb615ba339b0ebedc9d167771071703d4db3a77a3cb08205b080de13f3183d.php.txt)

**Comment by williamdes** [comment]
Hi @KimHEF 
I had a look to the code and could not find out a way to reproduce the error. I bet your table is maybe corrupt.
Could you give me the table structure please ?
What database do you use ?

**Comment by KimHEF** [comment]
> Hi @KimHEF
> I had a look to the code and could not find out a way to reproduce the error. I bet your table is maybe corrupt.
> Could you give me the table structure please ?
> What database do you use ?

Thanks william... i wanted to do that but now i am also can't replicate the issue. Don't know why but the Error is gone. Thank you so much for your help and i am really sorry for that.

**Comment by williamdes** [comment]
> > Hi @KimHEF
> > I had a look to the code and could not find out a way to reproduce the error. I bet your table is maybe corrupt.
> > Could you give me the table structure please ?
> > What database do you use ?
> 
> Thanks william... i wanted to do that but now i am also can't replicate the issue. Don't know why but the Error is gone. Thank you so much for your help and i am really sorry for that.

No worries, I am glad it is solved. If you have another issue feel free to create an issue for it, really

**Comment by garak** [comment]
@williamdes can you provide some information about closing?

**Comment by williamdes** [comment]
> @williamdes can you provide some information about closing?

Yes, I closed it because there is nothing I can do on my side

**Comment by williamdes** [comment]
This is being handed by an Ubuntu update (if it's accepted)
See https://github.com/phpmyadmin/phpmyadmin/issues/18498#issuecomment-1592981344 for a temporary fix of "Unknown named parameter $$dbi"
