### ISSUE TITLE
[Designer] removing a relation tries to remove the internal relation regardless of if the configuration storage is enabled

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16982]
### Describe the bug

Removing relations on the Designer tries to remove the internal relation even if the configuration storage is not enabled

### To Reproduce

1. Go to Designer
2. Remove a relation

### Expected behavior

Remove it without trying to remove the internal relation

### Server configuration

- phpMyAdmin version: 5.1

**Comment by williamdes** [comment]
This should explain reports of:
```
Warning: Undefined array key "relation"
#2 .\libraries\classes\Database\Designer\Common.php(18): callControllerForRoute
#1 .\libraries\classes\Database\Designer\Common.php(187): index
#0 .\libraries\classes\Database\Designer\Common.php(142): removeRelation
```

**Comment by williamdes** [comment]
This is also because the UI does not remove the relation and so the user can re-try to delete the relation, making the second part of the code be triggered.
This issue will be about the front and back end of this issue
