### ISSUE TITLE
Designer can't export a schema in pdf or svg

### ISSUE THREAD

**Issue by JoseHernan26** [phpmyadmin/phpmyadmin#17012]
### Describe the bug
Hello there!!

When i try to use Designer to export a schema of my database, it doesn't work.
This info is displayed when exporting on pdf:
```
Fatal error: Uncaught TypeError: ucfirst() expects parameter 1 to be string, null given in C:\xampp\phpMyAdmin\libraries\classes\Plugins\Schema\Pdf\Pdf.php:272 Stack trace: #0 C:\xampp\phpMyAdmin\libraries\classes\Plugins\Schema\Pdf\Pdf.php(272): ucfirst(NULL) #1 C:\xampp\phpMyAdmin\vendor\tecnickcom\tcpdf\tcpdf.php(3560): PhpMyAdmin\Plugins\Schema\Pdf\Pdf->Header() #2 C:\xampp\phpMyAdmin\vendor\tecnickcom\tcpdf\tcpdf.php(3227): TCPDF->setHeader() #3 C:\xampp\phpMyAdmin\vendor\tecnickcom\tcpdf\tcpdf.php(3139): TCPDF->startPage('P', '', false) #4 C:\xampp\phpMyAdmin\libraries\classes\Plugins\Schema\Pdf\PdfRelationSchema.php(493): TCPDF->AddPage('P') #5 C:\xampp\phpMyAdmin\libraries\classes\Plugins\Schema\Pdf\PdfRelationSchema.php(134): PhpMyAdmin\Plugins\Schema\Pdf\PdfRelationSchema->dataDictionaryDoc(Array) #6 C:\xampp\phpMyAdmin\libraries\classes\Plugins\Schema\SchemaPdf.php(129): PhpMyAdmin\Plugins\Schema\Pdf\PdfRelationSchema->__construct('bd-oberdan') #7 C:\xampp\phpMyAdmin\libraries\classes\Export.php(1223): PhpMyAdm in C:\xampp\phpMyAdmin\libraries\classes\Plugins\Schema\Pdf\Pdf.php on line 272
```
This info is displayed when exporting on svg:

```
Fatal error: Uncaught TypeError: XMLWriter::writeAttribute() expects parameter 2 to be string, float given in C:\xampp\phpMyAdmin\libraries\classes\Plugins\Schema\Svg\Svg.php:274 Stack trace: #0 C:\xampp\phpMyAdmin\libraries\classes\Plugins\Schema\Svg\Svg.php(274): XMLWriter->writeAttribute('x1', 307) #1 C:\xampp\phpMyAdmin\libraries\classes\Plugins\Schema\Svg\RelationStatsSvg.php(88): PhpMyAdmin\Plugins\Schema\Svg\Svg->printElementLine('line', 307, 224, 297, 224, 'stroke:#c00;str...') #2 C:\xampp\phpMyAdmin\libraries\classes\Plugins\Schema\Svg\SvgRelationSchema.php(267): PhpMyAdmin\Plugins\Schema\Svg\RelationStatsSvg->relationDraw(true) #3 C:\xampp\phpMyAdmin\libraries\classes\Plugins\Schema\Svg\SvgRelationSchema.php(161): PhpMyAdmin\Plugins\Schema\Svg\SvgRelationSchema->_drawRelations() #4 C:\xampp\phpMyAdmin\libraries\classes\Plugins\Schema\SchemaSvg.php(84): PhpMyAdmin\Plugins\Schema\Svg\SvgRelationSchema->__construct('bd-oberdan') #5 C:\xampp\phpMyAdmin\libraries\classes\Export.php(1223): PhpMyAdmin\Plugins\Schema\Sc in C:\xampp\phpMyAdmin\libraries\classes\Plugins\Schema\Svg\Svg.php on line 274
```

### To Reproduce

1. Go to 'Choose your database -  Go to designer'
2. Click on 'Export Schema- As PDF/SVG'

### Expected behavior

It should export a nice schema

### Server configuration

- Operating system: windows 10 64 bits
- Web server: xaamp
- Database version: Server: 127.0.0.1 via TCP/IP
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.4.14-MariaDB - mariadb.org binary distribution
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8mb4)

- PHP version: PHP version: 7.2.33
- phpMyAdmin version: Version information: 5.0.2

### Client configuration

- Browser: Chrome 

My email is: perezj861@gmail.com

**Comment by williamdes** [comment]
Hi @JoseHernan26
I think you should try the latest phpMyAdmin version (5.1.1 today)
Let me know if it works better
