### ISSUE TITLE
Issue with cabundle not installed, when using Git

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17151]
### Describe the bug

I don't have Composer installed nor CaBundle, when I'm using this repository on localhost. After commit https://github.com/phpmyadmin/phpmyadmin/pull/17143/commits/e5f90122806bea765825ed2c993136b501ed30dd, the commit info is no longer fetched and an error is thrown.

### Expected behavior

The error shouldn't be given, if the commit info cannot be loaded without CaBundle installed.

### Screenshots

![issue1](https://user-images.githubusercontent.com/25424343/137597647-e518ca51-ed24-4c9a-8829-a80afca95620.png)

### Server configuration

- Operating system: Windows 11
- Web server: nginx/1.21.3
- Database version: 5.7.35
- PHP version: 8.0.11
- phpMyAdmin version: 5.2.0-dev+20211015.8e46e96782

### Client configuration

- Browser: Firefox 95
- Operating system: Windows 11

### Additional context

```
2021/10/16 16:57:23 [error] 7952#25032: *3 FastCGI sent in stderr: "PHP Fatal error:  Uncaught Error: Class "Composer\CaBundle\CaBundle" not found in Z:\GitHub\phpmyadmin\libraries\classes\Utils\HttpRequest.php:194
Stack trace:
#0 Z:\GitHub\phpmyadmin\libraries\classes\Utils\HttpRequest.php(303): PhpMyAdmin\Utils\HttpRequest->curl('https://www.php...', 'GET', false, NULL, '')
#1 Z:\GitHub\phpmyadmin\libraries\classes\Git.php(426): PhpMyAdmin\Utils\HttpRequest->create('https://www.php...', 'GET')
#2 Z:\GitHub\phpmyadmin\libraries\classes\Git.php(581): PhpMyAdmin\Git->isRemoteCommit(Array, false, '8e46e967829a247...')
#3 Z:\GitHub\phpmyadmin\libraries\classes\Controllers\GitInfoController.php(38): PhpMyAdmin\Git->checkGitRevision()
#4 Z:\GitHub\phpmyadmin\libraries\classes\Routing.php(185): PhpMyAdmin\Controllers\GitInfoController->__invoke(Object(PhpMyAdmin\Http\ServerRequest), Array)
#5 Z:\GitHub\phpmyadmin\index.php(43): PhpMyAdmin\Routing::callControllerForRoute(Object(PhpMyAdmin\Http\ServerRequest), '/git-revision', Object(FastRoute\Dispatcher\GroupCountBased), Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#6 {main}
  thrown in Z:\GitHub\phpmyadmin\libraries\classes\Utils\HttpRequest.php on line 194" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /phpmyadmin/index.php?route=/git-revision&server=1&ajax_request=true&no_debug=true&_nocache=1634396243437875520&token=343f5e3365492c237a2c365d5d2a5f55 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1"
2021/10/16 16:58:20 [error] 7952#25032: *9 FastCGI sent in stderr: "PHP Fatal error:  Uncaught Error: Class "Composer\CaBundle\CaBundle" not found in Z:\GitHub\phpmyadmin\libraries\classes\Utils\HttpRequest.php:194
Stack trace:
#0 Z:\GitHub\phpmyadmin\libraries\classes\Utils\HttpRequest.php(303): PhpMyAdmin\Utils\HttpRequest->curl('https://www.php...', 'GET', false, NULL, '')
#1 Z:\GitHub\phpmyadmin\libraries\classes\VersionInformation.php(56): PhpMyAdmin\Utils\HttpRequest->create('https://www.php...', 'GET')
#2 Z:\GitHub\phpmyadmin\libraries\classes\Controllers\VersionCheckController.php(28): PhpMyAdmin\VersionInformation->getLatestVersion()
#3 Z:\GitHub\phpmyadmin\libraries\classes\Routing.php(185): PhpMyAdmin\Controllers\VersionCheckController->__invoke(Object(PhpMyAdmin\Http\ServerRequest), Array)
#4 Z:\GitHub\phpmyadmin\index.php(43): PhpMyAdmin\Routing::callControllerForRoute(Object(PhpMyAdmin\Http\ServerRequest), '/version-check', Object(FastRoute\Dispatcher\GroupCountBased), Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#5 {main}
  thrown in Z:\GitHub\phpmyadmin\libraries\classes\Utils\HttpRequest.php on line 194" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /phpmyadmin/index.php?route=/version-check HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1"
```

**Comment by liviuconcioiu** [comment]
> 
> 
> Hi @liviuconcioiu
> 
> Did you `composer update` ?
> 
> Ref: #17143

No, since I don't have composer installed. This is the problem.

**Comment by williamdes** [comment]
> > Hi @liviuconcioiu
> > Did you `composer update` ?
> > Ref: #17143
> 
> No, since I don't have composer installed. This is the problem.

Hmm, I did misunderstand then
How did you install phpMyAdmin ?
Is this a snapshot unzip ?

**Comment by williamdes** [comment]
You can use this script I made, it supports upgrades and keeps configs and of course snapshots!
https://gist.github.com/williamdes/883f2158f17e9ed5a83d892ada56f5df

**Comment by mauriciofauth** [comment]
> I'm using GitHub Desktop and I pull the commits.

There is no way that could work without running `composer update` and `yarn install` after every pull. You will end up with outdated dependencies, because the git repository does not contain all the necessary files to make phpMyAdmin work. The third-party packages and auto-generated files are not included. It is just a coincidence that the missing dependency has Composer as the vendor name, since it is a normal package like any other. 

If you want to keep your installation updated with the latest development version without having to use composer and yarn, you should have to install the daily snapshots that you can found at https://www.phpmyadmin.net/downloads/.
