### ISSUE TITLE
phpmyadmin broken after using `ppa:phpmyadmin/ppa` (unknown named parameter $$response - ContainerBuilder.php)

### ISSUE THREAD

**Issue by kanlukasz** [phpmyadmin/phpmyadmin#17187]
### Describe the bug

So far I have used `php7.x` and `phpmyadmin` from the official Ubuntu package (everything worked fine)
Now I have upgraded to `php8` using `ppa:ondrej` (all works fine here)

Then I wanted to update `phpmyadmin` according to this [documentation](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#ubuntu-ppa):
```
sudo add-apt-repository ppa:phpmyadmin/ppa
sudo apt-get update
sudo apt-get install phpmyadmin
```
### After that:
- I reloaded Apache
- cleared cache / cookies
- opened `localhost/phpmyadmin`

### And the effect is as follows:
```
Fatal error: Uncaught Error: Unknown named parameter $$response in /usr/share/php/Symfony/Component/DependencyInjection/ContainerBuilder.php:1140
Stack trace:
#0 /usr/share/php/Symfony/Component/DependencyInjection/ContainerBuilder.php(1140): ReflectionClass->newInstanceArgs()
#1 /usr/share/php/Symfony/Component/DependencyInjection/ContainerBuilder.php(609): Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#2 /usr/share/php/Symfony/Component/DependencyInjection/ContainerBuilder.php(555): Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#3 /usr/share/phpmyadmin/libraries/classes/Routing.php(186): Symfony\Component\DependencyInjection\ContainerBuilder->get()
#4 /usr/share/phpmyadmin/index.php(18): PhpMyAdmin\Routing::callControllerForRoute()
#5 {main} thrown in /usr/share/php/Symfony/Component/DependencyInjection/ContainerBuilder.php on line 1140
```

### Screenshots

![image](https://user-images.githubusercontent.com/30685349/142049235-398a6dc8-41da-4986-9282-2d5b497264fc.png)

### Server configuration

- Operating system: **Windows 10 with WSL2 - Ubuntu 20.04 focal**
- Web server: **Apache**
- Database version: **10.3.31-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04**
- PHP version:  **8.0.12**
- phpMyAdmin version: **from `ppa:phpmyadmin/ppa` (5.1.1)**

**Comment by williamdes** [comment]
Hi!
This looks just like https://github.com/phpmyadmin/phpmyadmin/issues/16968

Let me know if you find anything useful in #16968
This error is out of the scope of our code base unfortunately, it's a Symfony bug.

**Comment by kanlukasz** [comment]
Thank you for the quick reply.

I'm not sure if any solution from #16968 is okay with me, but maybe rolling back phpmyadmin can fix it temporarily? , for example to 5.0.X? Is it possible with your PPA? How?

Or any diffrent way? I generally don't need the latest version. I just want it to run on PHP 8

**Comment by williamdes** [comment]
It's not possible to have multiple versions on the PPA but you could try to install the deb from another source like another Ubuntu or Debian

See the [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

**Comment by williamdes** [comment]
The alternative could be to install phpMyAdmin by overriding the files in the installed directory by the extracted bundle from our [website](https://www.phpmyadmin.net/downloads/)

I feel wrong to not be able to provide a correct solution from a packaging perspective but I am not responsible of packaging the symfony packages. Anyway you already read the thread about all that complicated issue ^^

**Comment by kanlukasz** [comment]
Another idea that I have is to install phpmyadmin "independently".
I mean installation in `/var/www/*` via composer. What do you think about it ?

But here I have doubts about what to do with the current installation via ppa?
Can I somehow uninstall it safely? Should I do this?
Or should i rollback to official apt package? How? I feel very confused 😕 

_( I understand this is a phpmyadmin issue tracker and not an advice forum but would really appreciate a little help on this )_

**Comment by williamdes** [comment]
Hi @kanlukasz 

Did you try `apt purge phpmyadmin` to clean the installed package ?

I would suggest you to then use the zip file from our website

**Comment by INDIGO9777** [comment]
in nginx settings file switch php version from
fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
on the
fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
