### ISSUE TITLE
issues using phpmyadmin with latest softwares

### ISSUE THREAD

**Issue by MohammadMD1383** [phpmyadmin/phpmyadmin#17255]
### Describe the bug

When I open phpmyadmin on localhost it has many errors.
I'm using Ubuntu 21.10 - php 8.1 - mysql 8.0.27 - apache 2.4 - phpmyadmin 5.0

### To Reproduce

Just opening `localhost/phpmyadmin` is enough to face with a lot of trouble

### Client configuration

- Browser: edge
- Operating system: Ubuntu

### Additional context

the first problem was about that php couldn't find `Error.php`
I solved this by editing `ErrorHandler.php` and adding `require_once` to the file

then another problem is `storage_engine` which is removed from mysql 8

---
I have installed phpmyadmin from `apt`

**Comment by MohammadMD1383** [comment]
```
[Sat Dec 25 19:51:43.051642 2021] [php:notice] [pid 5616] [client ::1:53528] PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown system variable 'storage_engine' in /usr/share/phpmyadmin/libraries/classes/Dbi/DbiMysqli.php:199\nStack trace:\n#0 /usr/share/phpmyadmin/libraries/classes/Dbi/DbiMysqli.php(199): mysqli->query()\n#1 /usr/share/phpmyadmin/libraries/classes/DatabaseInterface.php(316): PhpMyAdmin\\Dbi\\DbiMysqli->realQuery()\n#2 /usr/share/phpmyadmin/libraries/classes/DatabaseInterface.php(1701): PhpMyAdmin\\DatabaseInterface->tryQuery()\n#3 /usr/share/php/Twig/Extension/CoreExtension.php(1544): PhpMyAdmin\\DatabaseInterface->fetchValue()\n#4 /var/lib/phpmyadmin/tmp/twig/15/155de66870dd527a6a36966da9d4af3b2bccecedd655d55c31f929dc5e947956.php(133): twig_get_attribute()\n#5 /usr/share/php/Twig/Template.php(394): __TwigTemplate_184024fbae3f64ac2ec6f7e4b2965c952858846650948f6b38ff25ad313385cd->doDisplay()\n#6 /usr/share/php/Twig/Template.php(367): Twig\\Template->displayWithErrorHandling()\n#7 /var/lib/phpmyadmin/tmp/twig/3f/3fc4c45f205288783b1b4ef49ed493aebca81df1b9df7eeee23449a41537aac7.php(224): Twig\\Template->display()\n#8 /usr/share/php/Twig/Template.php(394): __TwigTemplate_7fc8a2bae24fcdd2b89bf3b2a59765e5bee66c92320d227f8a059ba1c98c7134->doDisplay()\n#9 /usr/share/php/Twig/Template.php(367): Twig\\Template->displayWithErrorHandling()\n#10 /usr/share/php/Twig/Template.php(379): Twig\\Template->display()\n#11 /usr/share/php/Twig/TemplateWrapper.php(40): Twig\\Template->render()\n#12 /usr/share/phpmyadmin/libraries/classes/Template.php(134): Twig\\TemplateWrapper->render()\n#13 /usr/share/phpmyadmin/libraries/classes/Controllers/Database/StructureController.php(659): PhpMyAdmin\\Template->render()\n#14 /usr/share/phpmyadmin/libraries/classes/Controllers/Database/StructureController.php(172): PhpMyAdmin\\Controllers\\Database\\StructureController->displayTableList()\n#15 /usr/share/phpmyadmin/db_structure.php(56): PhpMyAdmin\\Controllers\\Database\\StructureController->index()\n#16 {main}\n\nNext Twig\\Error\\RuntimeError: An exception has been thrown during the rendering of a template ("Unknown system variable 'storage_engine'"). in /usr/share/phpmyadmin/templates/database/structure/body_for_table_summary.twig:42\nStack trace:\n#0 /usr/share/php/Twig/Template.php(367): Twig\\Template->displayWithErrorHandling()\n#1 /var/lib/phpmyadmin/tmp/twig/3f/3fc4c45f205288783b1b4ef49ed493aebca81df1b9df7eeee23449a41537aac7.php(224): Twig\\Template->display()\n#2 /usr/share/php/Twig/Template.php(394): __TwigTemplate_7fc8a2bae24fcdd2b89bf3b2a59765e5bee66c92320d227f8a059ba1c98c7134->doDisplay()\n#3 /usr/share/php/Twig/Template.php(367): Twig\\Template->displayWithErrorHandling()\n#4 /usr/share/php/Twig/Template.php(379): Twig\\Template->display()\n#5 /usr/share/php/Twig/TemplateWrapper.php(40): Twig\\Template->render()\n#6 /usr/share/phpmyadmin/libraries/classes/Template.php(134): Twig\\TemplateWrapper->render()\n#7 /usr/share/phpmyadmin/libraries/classes/Controllers/Database/StructureController.php(659): PhpMyAdmin\\Template->render()\n#8 /usr/share/phpmyadmin/libraries/classes/Controllers/Database/StructureController.php(172): PhpMyAdmin\\Controllers\\Database\\StructureController->displayTableList()\n#9 /usr/share/phpmyadmin/db_structure.php(56): PhpMyAdmin\\Controllers\\Database\\StructureController->index()\n#10 {main}\n  thrown in /usr/share/phpmyadmin/templates/database/structure/body_for_table_summary.twig on line 42
```

**Comment by williamdes** [comment]
Hi @MohammadMD1383 

You are probably not up to date, that said phpMyAdmin in Debian is not quite ready for PHP 8.1.
I would suggest you to use 8.0.

Please check the [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods) to be up to date with phpMyAdmin 5.1

You may also want to follow the 8.1 compatibility issue recap: #16746

**Comment by MohammadMD1383** [comment]
but how about the usage of `storage_engine`. As I searched it is removed from mysql.

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/phpmyadmin/blob/8fab4a7bfb0de97a4049a752cb466375d7872c61/templates/database/structure/body_for_table_summary.twig#L43

As you can see already 4 years ago this was conditional. So I am puzzled you still have the error

**Comment by MohammadMD1383** [comment]
I installed phpmyadmin from apt... is it possible that this problem caused by bad configuration when installing?

**Comment by williamdes** [comment]
> I installed phpmyadmin from apt... is it possible that this problem caused by bad configuration when installing?

Are you up to date to phpMyAdmin 5.1 ?
Ref: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

**Comment by MohammadMD1383** [comment]
from apt no. but I manually installed 5.1 from your website and that's all ok!

**Comment by williamdes** [comment]
> from apt no. but I manually installed 5.1 from your website and that's all ok!

Oh okay, perfect then
You can install from our PPA to have 5.1 but it will not be the same as an installed version from our website :)
So this is closed ?

**Comment by MohammadMD1383** [comment]
yes, thanks. this thread should be closed.
but as the last point, I should say that your ppa doesn't have releases for ubuntu 21 yet :)

**Comment by williamdes** [comment]
> yes, thanks. this thread should be closed. but as the last point, I should say that your ppa doesn't have releases for ubuntu 21 yet :)

Everything should be okay since then, it got fixed
