### ISSUE TITLE
Can´t create any query in phpmyadmin

### ISSUE THREAD

**Issue by celestinoxp** [phpmyadmin/phpmyadmin#17260]
### Describe the bug

Can´t create any query in phpmyadmin

### To Reproduce

1. click 1 table to see values
2. Click on 'sql' and create sql like "SELECT * FROM table WHERE 1"
3. Normally can see values of tables
4. Message with fatal error

### FATAL ERROR
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "PhpMyAdmin\Controllers\ImportController". in C:\xampp\phpMyAdmin\vendor\symfony\dependency-injection\ContainerBuilder.php:996 Stack trace: #0 C:\xampp\phpMyAdmin\vendor\symfony\dependency-injection\ContainerBuilder.php(590): Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition('PhpMyAdmin\\Cont...') #1 C:\xampp\phpMyAdmin\vendor\symfony\dependency-injection\ContainerBuilder.php(553): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('PhpMyAdmin\\Cont...', 1) #2 C:\xampp\phpMyAdmin\libraries\classes\Routing.php(186): Symfony\Component\DependencyInjection\ContainerBuilder->get('PhpMyAdmin\\Cont...') #3 C:\xampp\phpMyAdmin\index.php(43): PhpMyAdmin\Routing::callControllerForRoute(Object(PhpMyAdmin\Http\ServerRequest), '/import', Object(FastRoute\Dispatcher\GroupCountBased), Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #4 {main} thrown in C:\xampp\phpMyAdmin\vendor\symfony\dependency-injection\ContainerBuilder.php on line 996

### Server configuration

- Operating system: Windows 10
- Web server: Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/8.1.0-dev
- Database version: 10.5.14-MariaDB - MariaDB Server
- PHP version:  8.1.0-dev
- phpMyAdmin version: 5.2.0-dev

### Client configuration

- Browser: Google Chrome
- Operating system: Windows 10

**Comment by celestinoxp** [comment]
I have updated DependencyInjection with latest updates, problem continues...

**Comment by celestinoxp** [comment]
It works now. 
Updated in 2021-12-30.
