### ISSUE TITLE
Production PHPmyadmin 500 error on additional_service_enrollment table view

### ISSUE THREAD

**Issue by KTM25** [phpmyadmin/phpmyadmin#17428]
### Describe the bug

Currently seeing a 500 error when opening a table

### To Reproduce
**Query Being Run:**
```
SELECT * FROM `additional_service_enrollment` WHERE 1
```

**Schema:**

```
db-master-production.pr.smartpaymentplan.com/spp/additional_service_enrollment/		https://phpmyadmin-production.smartpaymentplan.com/index.php?route=/table/sql&db=spp&table=additional_service_enrollment
Your SQL query has been executed successfully.

explain  `service_enrollment`;

id	int(10) unsigned	NO	PRI	NULL	auto_increment	
id_additional_service	int(10) unsigned	NO	MUL	NULL		
id_account	int(10) unsigned	NO		NULL		
enrolled_on	datetime	NO		NULL		
canceled_on	datetime	YES		NULL	
```	

**Back Trace Exception:** 
```
Notice in ./libraries/classes/Display/Results.php#1047
 Undefined offset: 2

Backtrace

Results.php#1178: PhpMyAdmin\Display\Results->getTableHeadersForColumns(
array,
array,
array,
array,
array,
boolean false,
string 'SELECT * FROM `additional_service_enrollment` ',
)
Results.php#4248: PhpMyAdmin\Display\Results->getTableHeaders(
array,
array,
string 'SELECT * FROM `additional_service_enrollment` ',
array,
array,
array,
boolean false,
)
Sql.php#1371: PhpMyAdmin\Display\Results->getTable(
,
array,
array,
boolean false,
)
Sql.php#1624: PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(
,
string './themes/pmahomme/img/',
array,
boolean true,
string '1894',
integer 25,
NULL,
,
array,
)
Sql.php#1860: PhpMyAdmin\Sql->getQueryResponseForResultsReturned(
,
array,
string 'spp',
string 'additional_service_enrollment',
NULL,
,
string './themes/pmahomme/img/',
string '1894',
integer 25,
NULL,
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
Sql.php#1721: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean true,
string 'spp',
string 'additional_service_enrollment',
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
SqlController.php#219: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
array,
boolean true,
string 'spp',
string 'additional_service_enrollment',
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
Routing.php#191: PhpMyAdmin\Controllers\SqlController->index(array)
index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/sql',
,
,
)
Notice in ./libraries/classes/Display/Results.php#1051
 Undefined index: 

Backtrace

Results.php#1178: PhpMyAdmin\Display\Results->getTableHeadersForColumns(
array,
array,
array,
array,
array,
boolean false,
string 'SELECT * FROM `additional_service_enrollment` ',
)
Results.php#4248: PhpMyAdmin\Display\Results->getTableHeaders(
array,
array,
string 'SELECT * FROM `additional_service_enrollment` ',
array,
array,
array,
boolean false,
)
Sql.php#1371: PhpMyAdmin\Display\Results->getTable(
,
array,
array,
boolean false,
)
Sql.php#1624: PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(
,
string './themes/pmahomme/img/',
array,
boolean true,
string '1894',
integer 25,
NULL,
,
array,
)
Sql.php#1860: PhpMyAdmin\Sql->getQueryResponseForResultsReturned(
,
array,
string 'spp',
string 'additional_service_enrollment',
NULL,
,
string './themes/pmahomme/img/',
string '1894',
integer 25,
NULL,
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
Sql.php#1721: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean true,
string 'spp',
string 'additional_service_enrollment',
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
SqlController.php#219: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
array,
boolean true,
string 'spp',
string 'additional_service_enrollment',
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
Routing.php#191: PhpMyAdmin\Controllers\SqlController->index(array)
index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/sql',
,
,
)
Notice in ./libraries/classes/Display/Results.php#1051
 Trying to get property 'name' of non-object

Backtrace

Results.php#1178: PhpMyAdmin\Display\Results->getTableHeadersForColumns(
array,
array,
array,
array,
array,
boolean false,
string 'SELECT * FROM `additional_service_enrollment` ',
)
Results.php#4248: PhpMyAdmin\Display\Results->getTableHeaders(
array,
array,
string 'SELECT * FROM `additional_service_enrollment` ',
array,
array,
array,
boolean false,
)
Sql.php#1371: PhpMyAdmin\Display\Results->getTable(
,
array,
array,
boolean false,
)
Sql.php#1624: PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(
,
string './themes/pmahomme/img/',
array,
boolean true,
string '1894',
integer 25,
NULL,
,
array,
)
Sql.php#1860: PhpMyAdmin\Sql->getQueryResponseForResultsReturned(
,
array,
string 'spp',
string 'additional_service_enrollment',
NULL,
,
string './themes/pmahomme/img/',
string '1894',
integer 25,
NULL,
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
Sql.php#1721: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean true,
string 'spp',
string 'additional_service_enrollment',
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
SqlController.php#219: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
array,
boolean true,
string 'spp',
string 'additional_service_enrollment',
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
Routing.php#191: PhpMyAdmin\Controllers\SqlController->index(array)
index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/sql',
,
,
)
Notice in ./libraries/classes/Display/Results.php#1056
 Undefined index: 

Backtrace

Results.php#1178: PhpMyAdmin\Display\Results->getTableHeadersForColumns(
array,
array,
array,
array,
array,
boolean false,
string 'SELECT * FROM `additional_service_enrollment` ',
)
Results.php#4248: PhpMyAdmin\Display\Results->getTableHeaders(
array,
array,
string 'SELECT * FROM `additional_service_enrollment` ',
array,
array,
array,
boolean false,
)
Sql.php#1371: PhpMyAdmin\Display\Results->getTable(
,
array,
array,
boolean false,
)
Sql.php#1624: PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(
,
string './themes/pmahomme/img/',
array,
boolean true,
string '1894',
integer 25,
NULL,
,
array,
)
Sql.php#1860: PhpMyAdmin\Sql->getQueryResponseForResultsReturned(
,
array,
string 'spp',
string 'additional_service_enrollment',
NULL,
,
string './themes/pmahomme/img/',
string '1894',
integer 25,
NULL,
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
Sql.php#1721: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean true,
string 'spp',
string 'additional_service_enrollment',
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
SqlController.php#219: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
array,
boolean true,
string 'spp',
string 'additional_service_enrollment',
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
Routing.php#191: PhpMyAdmin\Controllers\SqlController->index(array)
index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/sql',
,
,
)
Notice in ./libraries/classes/Display/Results.php#1062
 Undefined index: 

Backtrace

Results.php#1178: PhpMyAdmin\Display\Results->getTableHeadersForColumns(
array,
array,
array,
array,
array,
boolean false,
string 'SELECT * FROM `additional_service_enrollment` ',
)
Results.php#4248: PhpMyAdmin\Display\Results->getTableHeaders(
array,
array,
string 'SELECT * FROM `additional_service_enrollment` ',
array,
array,
array,
boolean false,
)
Sql.php#1371: PhpMyAdmin\Display\Results->getTable(
,
array,
array,
boolean false,
)
Sql.php#1624: PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(
,
string './themes/pmahomme/img/',
array,
boolean true,
string '1894',
integer 25,
NULL,
,
array,
)
Sql.php#1860: PhpMyAdmin\Sql->getQueryResponseForResultsReturned(
,
array,
string 'spp',
string 'additional_service_enrollment',
NULL,
,
string './themes/pmahomme/img/',
string '1894',
integer 25,
NULL,
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
Sql.php#1721: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean true,
string 'spp',
string 'additional_service_enrollment',
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
SqlController.php#219: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
array,
boolean true,
string 'spp',
string 'additional_service_enrollment',
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
Routing.php#191: PhpMyAdmin\Controllers\SqlController->index(array)
index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/sql',
,
,
)
Notice in ./libraries/classes/Display/Results.php#1635
 Trying to get property 'name' of non-object

Backtrace

Results.php#1071: PhpMyAdmin\Display\Results->getOrderLinkAndSortedHeaderHtml(
NULL,
array,
array,
NULL,
string 'SELECT * FROM `additional_service_enrollment` ',
integer 25,
string '',
array,
array,
NULL,
)
Results.php#1178: PhpMyAdmin\Display\Results->getTableHeadersForColumns(
array,
array,
array,
array,
array,
boolean false,
string 'SELECT * FROM `additional_service_enrollment` ',
)
Results.php#4248: PhpMyAdmin\Display\Results->getTableHeaders(
array,
array,
string 'SELECT * FROM `additional_service_enrollment` ',
array,
array,
array,
boolean false,
)
Sql.php#1371: PhpMyAdmin\Display\Results->getTable(
,
array,
array,
boolean false,
)
Sql.php#1624: PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(
,
string './themes/pmahomme/img/',
array,
boolean true,
string '1894',
integer 25,
NULL,
,
array,
)
Sql.php#1860: PhpMyAdmin\Sql->getQueryResponseForResultsReturned(
,
array,
string 'spp',
string 'additional_service_enrollment',
NULL,
,
string './themes/pmahomme/img/',
string '1894',
integer 25,
NULL,
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
Sql.php#1721: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean true,
string 'spp',
string 'additional_service_enrollment',
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
SqlController.php#219: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
array,
boolean true,
string 'spp',
string 'additional_service_enrollment',
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
string 'SELECT * FROM `additional_service_enrollment`',
NULL,
)
Routing.php#191: PhpMyAdmin\Controllers\SqlController->index(array)
index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/sql',
,
,
)
```
### Logs
```
[Mon Feb 21 07:38:30.999706 2022] [php7:error] [pid 18907] [client 10.0.1.28:65123] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to PhpMyAdmin\\Display\\Results::getSortOrderHiddenInputs() must be of the type string, null given, called in /var/www/html/phpmyadmin/libraries/classes/Display/Results.php on line 1691 and defined in /var/www/html/phpmyadmin/libraries/classes/Display/Results.php:2028\nStack trace:\n#0 /var/www/html/phpmyadmin/libraries/classes/Display/Results.php(1691): PhpMyAdmin\\Display\\Results->getSortOrderHiddenInputs(Array, NULL)\n#1 /var/www/html/phpmyadmin/libraries/classes/Display/Results.php(1071): PhpMyAdmin\\Display\\Results->getOrderLinkAndSortedHeaderHtml(NULL, Array, Array, NULL, 'SELECT * FROM `...', 25, '', Array, Array, NULL)\n#2 /var/www/html/phpmyadmin/libraries/classes/Display/Results.php(1178): PhpMyAdmin\\Display\\Results->getTableHeadersForColumns(Array, Array, Array, Array, Array, false, 'SELECT * FROM `...')\n#3 /var/www/html/phpmyadmin/libraries/classes/Display/Results.php(4244): PhpMyAdmin\\Display\\Results->getTableHeaders(Array, Array, 'SELECT * FROM `...', Array, Array,  in /var/www/html/phpmyadmin/libraries/classes/Display/Results.php on line 2028
```

### Vulnerable Since
`14.9.7`

### What we have done
```
We have installed the latest 5.1.3 versions as well as upgraded themes and are experiencing the same issues 
```

### Server configuration
```
PHP Version	7.2.24-0ubuntu0.18.04.7
SERVER_SOFTWARE	Apache/2.4.46 (Ubuntu)
```

**Comment by williamdes** [comment]
Hi @KTM25 
Thank you for the report !
Could you send the SQL structure of the two tables mentioned ?

**Comment by KTM25** [comment]
Hi @williamdes, sorry for responding so late. Is there a way to send the SQL structure securely?

**Comment by KTM25** [comment]
Hi @williamdes My boss was wondering if there is a way to send this securely as they don't want the information public

**Comment by williamdes** [comment]
> Hi @williamdes My boss was wondering if there is a way to send this securely as they don't want the information public.

Hi!
Sorry for the delayed reply
You can email me at williamdes@wdes.fr
And if you have a GPG key you can encrypt the data
My public key is on my website: https://williamdes.eu/public-key.asc

Thanks in advance for helping debug

**Comment by KTM25** [comment]
No worries! 
Email titled as MySQL Table Structure

**Comment by williamdes** [comment]
> No worries! 
> Email titled as MySQL Table Structure

Thank you, I received it and will process it as soon as possible when I am back on my laptop

**Comment by KTM25** [comment]
Hi @williamdes,

Just curious if there is any update to this? 

Thanks!

**Comment by KTM25** [comment]
Hey @williamdes 

Hope all is well, just wanting to checkin. 

Appreciate it!

**Comment by williamdes** [comment]
> Hey @williamdes
> 
> Hope all is well, just wanting to checkin.
> 
> Appreciate it!

Hey @KTM25 
I am really sorry for the time this takes. Still under a lot of work to do at work.
But I did not forget you

Can you let me know if when you export to SQL the table and then create a new database and import the SQL dump you still have the error ?

**Comment by williamdes** [comment]
Could be similar to #17498

**Comment by williamdes** [comment]
Hi @KTM25 
Could you test the patch 29170a28f97a2d459bec6d2cf3da69feb614953f and let me know if it works ?
I re-generated the 5.1 snapshot: [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot)
