### ISSUE TITLE
Fatal error: Unsupported operand types in Results.php

### ISSUE THREAD

**Issue by jbartak** [phpmyadmin/phpmyadmin#17434]
### Describe the bug

`SHOW PROCESSLIST;` throws a fatal error in version 4.9.8:
```
PHP Fatal error:  Uncaught Error: Unsupported operand types in /usr/share/phpMyAdmin/libraries/classes/Display/Results.php:5608\nStack trace:\n#0 /usr/share/phpMyAdmin/libraries/classes/Display/Results.php(3521): PhpMyAdmin\\Display\\Results->_getCheckboxAndLinks('left', 'sql.php', Array, 0, '.`Id` = 3349506...', '.`Id` = 3349506...', Array, NULL, NULL, NULL, NULL, NULL, '<span class="no...', 'KILL 33495067;', NULL, Array)\n#1 /usr/share/phpMyAdmin/libraries/classes/Display/Results.php(2667): PhpMyAdmin\\Display\\Results->_getPlacedLinks('left', 'sql.php', Array, 0, '.`Id` = 3349506...', '.`Id` = 3349506...', Array, NULL, NULL, NULL, NULL, NULL, '<span class="no...', 'KILL 33495067;', NULL, Array)\n#2 /usr/share/phpMyAdmin/libraries/classes/Display/Results.php(4289): PhpMyAdmin\\Display\\Results->_getTableBody(Object(mysqli_result), Array, Array, Array, false)\n#3 /usr/share/phpMyAdmin/libraries/classes/Sql.php(1759): PhpMyAdmin\\Display\\Results->getTable(Object(mysqli_result), Array, Array, false)\n#4 /usr/share/phpMyAdmin/libraries/class in /usr/share/phpMyAdmin/libraries/classes/Display/Results.php on line 5608
```

### To Reproduce

1. Open PMAs SQL Editor.
2. Type in "SHOW PROCESSLIST;"
3. Click OK to execute the query

An internal server error (500) is shown.

### Expected behavior

Showing the process list's results in PMA.

### Screenshots

N/A

### Server configuration

- Operating system: centos-release-7-8.2003.0.el7.centos.x86_64
- Web server: httpd-2.4.6-97.el7.centos.4.x86_64
- Database version: mysql-community-server-5.6.49-2.el6.x86_64
- PHP version: 7.4.28
- phpMyAdmin version: phpMyAdmin49-4.9.8-1.el7.ius.noarch

### Client configuration

- Browser: Chrome 98.0.4758.102
- Operating system: Debian 11

### Additional context

https://github.com/phpmyadmin/phpmyadmin/issues/17315 looks to be similiar.

**Comment by williamdes** [comment]
Hi @jbartak 
I would suggest you to apply this patch: https://github.com/phpmyadmin/phpmyadmin/commit/3bd3ee074c9c1af8ba3b8c20880f20b7875ac97c#diff-6a82aee55be3c2036240f864d5d4666c8379558893e70fe2484041a0c2deb57fR2523 or to upgrade to 5.1.3 if it is packaged :)

Let me know
