### ISSUE TITLE
Unable to display errors before dbi init

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#17527]
### Describe the bug

```html
<br />
<b>Fatal error</b>:  Uncaught TypeError: PhpMyAdmin\ConfigStorage\Relation::__construct(): Argument #1 ($dbi) must be of type PhpMyAdmin\DatabaseInterface, null given, called in libraries/classes/Twig/RelationExtension.php on line 24 and defined in libraries/classes/ConfigStorage/Relation.php:62
Stack trace:
#0 libraries/classes/Twig/RelationExtension.php(24): PhpMyAdmin\ConfigStorage\Relation-&gt;__construct(NULL)
#1 vendor/twig/twig/src/ExtensionSet.php(426): PhpMyAdmin\Twig\RelationExtension-&gt;getFunctions()
#2 vendor/twig/twig/src/ExtensionSet.php(411): Twig\ExtensionSet-&gt;initExtension(Object(PhpMyAdmin\Twig\RelationExtension))
#3 vendor/twig/twig/src/ExtensionSet.php(385): Twig\ExtensionSet-&gt;initExtensions()
#4 vendor/twig/twig/src/Environment.php(810): Twig\ExtensionSet-&gt;getUnaryOperators()
#5 vendor/twig/twig/src/Lexer.php(457): Twig\Environment-&gt;getUnaryOperators()
#6 vendor/twig/twig/src/Lexer.php(108): Twig\Lexer-&gt;getOperatorRegex()
#7 vendor/twig/twig/src/Environment.php(466): Twig\Lexer-&gt;__construct(Object(Twig\Environment))
#8 vendor/twig/twig/src/Environment.php(516): Twig\Environment-&gt;tokenize(Object(Twig\Source))
#9 vendor/twig/twig/src/Environment.php(348): Twig\Environment-&gt;compileSource(Object(Twig\Source))
#10 vendor/twig/twig/src/Environment.php(309): Twig\Environment-&gt;loadTemplate('__TwigTemplate_...', 'error/generic.t...')
#11 libraries/classes/Template.php(123): Twig\Environment-&gt;load('error/generic.t...')
#12 libraries/classes/Template.php(156): PhpMyAdmin\Template-&gt;load('error/generic')
#13 libraries/classes/Core.php(145): PhpMyAdmin\Template-&gt;render('error/generic', Array)
#14 libraries/classes/Config.php(684): PhpMyAdmin\Core::fatalError('Wrong permissio...')
#15 libraries/classes/Common.php(169): PhpMyAdmin\Config-&gt;checkPermissions()
#16 index.php(40): PhpMyAdmin\Common::run()
#17 {main}
  thrown in <b>libraries/classes/ConfigStorage/Relation.php</b> on line <b>62</b><br />
```

### To Reproduce

1. `chmod 777 config.inc.php`

### Expected behavior

See error

### Screenshots

White page or trace if `$cfg['environment'] = 'development';`

### Server configuration

- PHP version: 8.1
- phpMyAdmin version: 5.2

**Comment by stbr0131** [comment]
@williamdes not the best way to repair but it's functional
