### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'value') and Undefined index: pred_hostname

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17547]
### Describe the bug

It happens when you edit privileges for a user account on a specific database.

### To Reproduce

1. Edit privileges for a user account on a specific database
2. Click on 'Go'
3. See error

### Expected behavior

No error should be given.

### Screenshots

https://user-images.githubusercontent.com/25424343/169705655-0496b2f3-f5b2-47e6-8679-6bbae98ad971.mp4

### Server configuration

- Operating system: Linux
- Web server: nginx/1.14.2
- Database version: 8.0.18 - MySQL Community Server - GPL
- PHP version: 7.4.29
- phpMyAdmin version: 5.3.0-dev

### Client configuration

- Browser: Chrome/101.0.4951.67
- Operating system: Windows 10

### Additional context

```
tracekit.js?v=5.3.0-dev:342 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at HTMLFormElement.handleEvent (privileges.js:444:39)
    at HTMLFormElement.newFunc (error_report.js:247:33)
    at HTMLFormElement.dispatch (jquery.min.js?v=5.3.0-dev:2:43064)
    at HTMLFormElement.v.handle (jquery.min.js?v=5.3.0-dev:2:41048)
```

```
Notice in ./libraries/classes/Server/Privileges.php#2566

 Undefined index: pred_hostname
Backtrace

PrivilegesController.php#220: PhpMyAdmin\Server\Privileges->addUser(
NULL,
string '',
string '',
string '*6E1D683C148B73830421F1D93529DC187CF45107',
boolean false,
)
Routing.php#189: PhpMyAdmin\Controllers\Server\PrivilegesController->__invoke(
,
array,
)
index.php#44: PhpMyAdmin\Routing::callControllerForRoute(
,
string '/server/privileges',
,
,
)
```

**Comment by liviuconcioiu** [comment]
On 6.0.0-dev, this error is given

`TypeError: PhpMyAdmin\Server\Privileges::setUserGroup(): Argument #1 ($username) must be of type string, null given, called in /home/demo/.pma-demo/master-config/libraries/classes/Server/Privileges.php on line 2365`

**Comment by kamil-tekiela** [comment]
I am looking into this, but do you know what the correct behaviour should be? What should actually happen after you click go? It's not like there are any input fields to change any information on this page.

**Comment by liviuconcioiu** [comment]
> I am looking into this, but do you know what the correct behaviour should be? What should actually happen after you click go? It's not like there are any input fields to change any information on this page.

I think this message should be shown, if `Go` is clicked.

`Username and hostname didn't change. If you only want to change the password, 'Change password' tab should be used.`

For example, the `Login Information` tab, contains a form when you edit user privileges, but this form is missing when a databases is selected.

![1](https://github.com/phpmyadmin/phpmyadmin/assets/25424343/6ef34522-a865-4830-9fd4-08e136d7823b)
![2](https://github.com/phpmyadmin/phpmyadmin/assets/25424343/a4a593c2-e623-43c4-81b1-871e08f6c932)

@williamdes thoughts?

**Comment by kamil-tekiela** [comment]
That would make this tab completely useless. I have a feeling this tab should not be available when database is selected. I can't imagine any reason to use it.

**Comment by williamdes** [comment]
it really feels weird all that stuff about re creating the user or adding a new one when you just want to edit it

In this case I do not see why there should be an error
The code is probably deeply broken, the pred_* stuff always comes back in corner cases
We should refactor it in a cleaner way

**Comment by williamdes** [comment]
The pred_* globals are gone in #19503

- https://github.com/phpmyadmin/phpmyadmin/pull/19503/commits/c481ab304ab8562097792d5dd767152059135803
- https://github.com/phpmyadmin/phpmyadmin/pull/19503/commits/64f86ad4fe5660dd682cc288c7f8661ddc75b0b7

I guess this would need a new full testing for 6.0
