### ISSUE TITLE
phpmyadmin Login issue WD myCloud Ultra Ex2 mysqli::real_connect(): (HY000/2002): Connection refused (related #18206)

### ISSUE THREAD

**Issue by Liese2007** [phpmyadmin/phpmyadmin#18875]
### Describe the bug

Hi,
I am trying to setup a mysql server on a WD MyCloud Ex2 Ultra but I cannot login with initial login acc. WD:
login: root 
PW: empty

My issue seems very similar to the issue #18206
Screenshots are similar.

My WD NAS Firmware is the actual one: 5.27.157
I have installed the WD phpmyadmin version 1.14 via Frontend (and meanwhile as well manually (still via frontend))
Latest release notes:
This release note provides information on the following:

> Version 1.14 - March 13, 2023
Version 1.13 - April 29, 2021
Version 1.12 - February 2, 2021
Version 1.11 - September 11, 2020
Version 1.09 - September 10, 2020
Version 1.07 - June 2, 2020
Revision 1.14
Update version to 5.0.4+dfsg2-2+deb11u1

The SSH login using sshd as root and executing the WD recommended command 

> python3 /usr/bin/mysql_reset.py -r

doesn't reset the root login issue.
command line output:

> root@LieseUltra ~ # python3 /usr/bin/mysql_reset.py -r
> killall: mysqld: no process killed
> killall: mysqld_safe: no process killed
> killall: mariadbd: no process killed
> killall: mariadbd-safe: no process killed
> 231230 15:46:48 mysqld_safe Logging to '/mnt/HD_a4/.@database@/LieseUltra.err'.
> 231230 15:46:48 mysqld_safe Starting mariadbd daemon with databases from /mnt/HD_a4/.@database@
> Traceback (most recent call last):
>   File "/usr/bin/mysql_reset.py", line 748, in <module>
>     reset_root_account()
>   File "/usr/bin/mysql_reset.py", line 585, in reset_root_account
>     if not _get_datadir_from_process_list():
>   File "/usr/bin/mysql_reset.py", line 72, in _get_datadir_from_process_list
>     datadir = output.decode().strip().split("/usr/libexec/mariadbd")[1].split("--datadir=")[1].split(" ")[0]
> IndexError: list index out of range

I still get 
**mysqli::real_connect(): (HY000/2002): Connection refused**

I tried as well several standard login / Password combinations, like
admin / empty
admin / admin
root / empty

### Expected behavior

After executing the 
python3 /usr/bin/mysql_reset.py -r
command WD indicates that the password should be reset. 

### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system: WD MyCloud OS5 Version 5.27.157
- Web server:  --- no idea what to check ---
- Database version:  mysql  Ver 15.1 Distrib 10.5.19-MariaDB, for Linux (arm) using readline 5.1
- PHP version:  PHP 7.4.33 (cli) (built: Jul 27 2023 09:11:49) ( NTS )
   Copyright (c) The PHP Group
    Zend Engine v3.4.0, Copyright (c) Zend Technologies
- phpMyAdmin version: WD 1.14 / 5.0.4 acc. release notes

- on the WD MyCloud the Network Database setting is "ON with remote access"
### Client configuration

- Browser:  Chrome
- Operating system: Windows 11

### Additional context

I hope my explanation is clear....

**Comment by Liese2007** [comment]
After almost a year I tried now again. 
It's still not working.
Software version 1.17 acc WDMyCloud Interface

**Comment by williamdes** [comment]
Hi @Liese2007 

I do not think this is a phpMyAdmin bug, but we can still help you access the DB.

> 5.0.4+dfsg2-2+deb11u1

You are using the Debian distributed version, this is great.

To change the password you can use the `--skip-grant-tables` CLI option of MySQL/MariaDB: https://dev.mysql.com/doc/refman/8.4/en/resetting-permissions.html
